### ISSUE TITLE
Creating account issue

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#101]
creating an account doesn't work sometimes. After clicking on "Create an account" I get

![image](https://cloud.githubusercontent.com/assets/2411066/20834775/4b6dee52-b897-11e6-8b35-a5cb41e5cafc.png)

Trying with my adrianahomolova@oneworld.nl on Chrome 54.0.2840.100

My colleague also said that once she used a password with a number it worked. Are there restrictions on the password length / types of characters?

**Comment by nightsh** [comment]
My guess is you entered a short password, a taken email or it was a mismatch between pwd and confirmation. We do have errors in the network tab, will show on the UI as well (had to perform a notification service update before, then got carried away, so thanks for the heads up).

![image](https://cloud.githubusercontent.com/assets/1579997/21061893/088986ee-be57-11e6-9acb-556a3330bc12.png)

**Comment by zufanka** [comment]
can we put requirements for password in here?

![image](https://cloud.githubusercontent.com/assets/2411066/21083117/93414e5a-bfe9-11e6-91e6-4fb5995c25f5.png)
