### ISSUE TITLE
Confimation email ending up in spamfolder

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#102]
Is there something to do about this? Make it look less like spam? :)

**Comment by nightsh** [comment]
We have no reputation on sending emails, good or bad, since our domain is quite new. I think we need to let Google get used to it for a while.

In the meantime, double checking everything works flawlessly is the best I can do. It has no thing to do with the frontend, however. Closing it :-)

**Comment by nightsh** [comment]
We also took action on backend issue tenders-exposed/elvis-backend#34
