### ISSUE TITLE
IT is not a part of Real Estate services

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#106]
![image](https://cloud.githubusercontent.com/assets/2411066/21082866/ccf03508-bfe4-11e6-916f-b692d82c0c25.png)

these are the 1st level CPV codes that need to be on the top of the tree
`csvgrep -c 3 -r '2|0'` [cpvcodes.csv](https://github.com/opented/opented/blob/master/cpvcodes/cpvcodes.csv)

PLAIN_CODE,REAL_CODE,NAME
3000000,3,"Agricultural, farming, fishing, forestry and related products"
9000000,9,"Petroleum products, fuel, electricity and other sources of energy"
14000000,14,"Mining, basic metals and related products"
15000000,15,"Food, beverages, tobacco and related products"
16000000,16,Agricultural machinery
18000000,18,"Clothing, footwear, luggage articles and accessories"
19000000,19,"Leather and textile fabrics, plastic and rubber materials"
22000000,22,Printed matter and related products
24000000,24,Chemical products
30000000,,"Office and computing machinery, equipment and supplies except furniture and software packages"
31000000,31,"Electrical machinery, apparatus, equipment and consumables; lighting"
32000000,32,"Radio, television, communication, telecommunication and related equipment"
33000000,33,"Medical equipments, pharmaceuticals and personal care products"
34000000,34,Transport equipment and auxiliary products to transportation
35000000,35,"Security, fire-fighting, police and defence equipment"
37000000,37,"Musical instruments, sport goods, games, toys, handicraft, art materials and accessories"
38000000,38,"Laboratory, optical and precision equipments (excl. glasses)"
39000000,39,"Furniture (incl. office furniture), furnishings, domestic appliances (excl. lighting) and cleaning products"
41000000,41,Collected and purified water
42000000,42,Industrial machinery
43000000,43,"Machinery for mining, quarrying, construction equipment"
44000000,44,Construction structures and materials; auxiliary products to construction (except electric apparatus)
45000000,45,Construction work
48000000,48,Software package and information systems
50000000,,Repair and maintenance services
51000000,51,Installation services (except software)
55000000,55,"Hotel, restaurant and retail trade services"
60000000,,Transport services (excl. Waste transport)
63000000,63,Supporting and auxiliary transport services; travel agencies services
64000000,64,Postal and telecommunications services
65000000,65,Public utilities
66000000,66,Financial and insurance services
70000000,,Real estate services
71000000,71,"Architectural, construction, engineering and inspection services"
72000000,72,"IT services: consulting, software development, Internet and support"
73000000,73,Research and development services and related consultancy services
75000000,75,"Administration, defence and social security services"
76000000,76,Services related to the oil and gas industry
77000000,77,"Agricultural, forestry, horticultural, aquacultural and apicultural services"
79000000,79,"Business services: law, marketing, consulting, recruitment, printing and security"
80000000,,Education and training services
85000000,85,Health and social work services
90000000,,"Sewage, refuse, cleaning and environmental services"
92000000,92,"Recreational, cultural and sporting services"
98000000,98,"Other community, social and personal services"

**Comment by nightsh** [comment]
Temporarily blocked by tenders-exposed/elvis-backend#38

**Comment by nightsh** [comment]
Unblocked, fixing in progress.
