### ISSUE TITLE
"Stabilizing" doesn't always look pretty

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#107]
![image](https://cloud.githubusercontent.com/assets/2411066/21082973/2346288e-bfe7-11e6-9ae4-b1294edc3456.png)

**Comment by nightsh** [comment]
Will update the loading animation to make it prettier :)

**Comment by chutko** [comment]
i will design something

**Comment by nightsh** [comment]
Blocked by #88. Loader isn't consistent at the moment, once we have the same loader throughout the app we can implement a design. Nothing stopping us from designing one in the meantime, though, but I'm afraid there would be some implementation constraints we're not aware of yet.

**Comment by chutko** [comment]
i think we should consider the whole loading throughout the system in this issue. three types of *loading* elements come to my mind: 
1. small component loading - for cases when just a single component is (re)loading, for example button of submitted form waiting for response. 
example: http://codepen.io/jmalatia/pen/HkmaA
2. page/big area loading - when whole screen or big content area is being loaded, the area should become unable to interact with, covered with overlay and a spinner
example: https://www.tjvantoll.com/demos/2013-04-24/loading
3. network rendering - the whole process of network rendering between clicking the "visualise" button and displaying the network which is ready to be used, should be displayed as a progress bar with description. everything loading on the background should be described within the progress bar. just "Loading..." is too boring. the user should know more about what is currently being loaded - for example Requesting data, Loading database, Filtering data, Creating network map etc

**Comment by zufanka** [comment]
Closing, discussion and progress in #88 !
