### ISSUE TITLE
Missing count by relationships

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#109]
![image](https://cloud.githubusercontent.com/assets/2411066/21083007/b484fff0-bfe7-11e6-8bab-56bec7d1a216.png)

**Comment by zufanka** [comment]
Chrome / 54.0.2840.100 (64-bit) / Fedora 24
network ID 5856f5a22dcb56605e000020

**Comment by nightsh** [comment]
I forgot to ask, but was this on staging or production?

**Comment by zufanka** [comment]
Staging!
