### ISSUE TITLE
Chose colors for different types of nodes

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#110]
I am now drawing a network of Netherlands and Germany for a specific market.
I would like to visually differentiate between the nodes not only as Procurer - Supplier, but also as Netherlands / Germany (and 'both' if one company is active in both markets). This can be useful for the future for other filters and options such as for example marking least competitive companies red or so.

**Comment by zufanka** [comment]
@chutko ?

**Comment by chutko** [comment]
we could display tiny flags somewhere around the label. but have in mind as we keep adding stuff to each node, things will get visually more clutered

**Comment by zufanka** [comment]
A complex problem to solve, closing for now.

**Comment by zufanka** [comment]
A complex problem to solve, closing for now.
