### ISSUE TITLE
Make additional pages on the website

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#111]
- terms & conditions
- about
- data license
- CPV explanation

Talk to Matej about the best design options

**Comment by nightsh** [comment]
Wouldn't be better to group all the nerdy things in one page: t&c, licenses, glossary, methodology?
Can't really figure out a name for it, and I'm not gonna think about it unless it's a popular enough idea :)

I'm favouring longer and richer pages than scattered information. We can even have more links than pages, say the four above would be four different links leading to different sections of the nerdy page.

What do you guys think? Ping @zufanka and @chutko

**Comment by chutko** [comment]
i think what @zufanka proposes is fine. this is how i think about the content:

*Terms & Conditions* - this kind of page is almost a standard. it is related to Data Licence, maybe these two can be merged or at least linked together

*About* - if somebody is searching for something like "public spending (data) visualisation (tool)", this page (or homepage) should appear in the results. The content should include: the idea behind elvis, screenshots, UI description, team, partners. It could be split into several sections for the start, later we can put it on separate pages if we have enough content

*Methodology* - this topic should be separate as it will probably contain enough information itself - general exaplanation of node graph theory and its application in elvis, link to @zufanka 's thesis or other resources, types of red flags and their visual examples, description of used data, maybe even technology used to process and visualise it. this page should be linked to CPV info and About pages

*CPV info* - this information is related to elvis indirectly, it should explain the CPV codes in general and their relation to elvis

*Contact* - simple page with contact info and communication channels (github, twitter, youtube etc)

**Comment by chutko** [comment]
i have improved the contact page so far. will slowly take a look at other pages too

**Comment by zufanka** [comment]
these two still need some prettifying ^^

http://tenders.exposed/terms-conditions
http://tenders.exposed/about

**Comment by zufanka** [comment]
@chutko do we still need this issue to be open?

**Comment by chutko** [comment]
there are still few more to go: settings, my projects, terms and conditions. 
but i can split them into separate issues

**Comment by zufanka** [comment]
@chutko that means this one can be closed?

**Comment by chutko** [comment]
yep :)
