### ISSUE TITLE
sorting in the side panel does not work in Safari

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#118]
safari 9.1.3.
OSX 10.9.5

sorting on the side panel sometimes  works and sometimes it doesn’t.
I found no errors in the console.

**Comment by nightsh** [comment]
Oh that's weird. And I don't have a Safari anywhere, need an iThing for it. Bummer.

**Comment by zufanka** [comment]
Sorting on the sidebar is now completely gone :)

![image](https://user-images.githubusercontent.com/2411066/28427069-547ace1e-6d75-11e7-8758-9cf1ae95caea.png)

**Comment by chutko** [comment]
haha its gone because i made it disappear :)

the original design of sorting was supposed to be using a select (sort by) and button (order by)
![elvis-sidebar-sorting](https://user-images.githubusercontent.com/4135015/28490774-a13008aa-6ee2-11e7-9fd5-69ba9b25cee8.png)

displaying the table head and sorting by clicking on columns in a data table seemed weird when there are just 2 columns and it is obvious what is what. so lets implement the select in this issue, shall we?

**Comment by zufanka** [comment]
@chutko soo .. are you going to redesign this or implement the above?

**Comment by ca1yps0** [comment]
ok. we can implement as the original design. can someone please tell me what the select options should be?

**Comment by zufanka** [comment]
@ca1yps0 I think for now it's enough to sort according to:
- the value in the circle
- name (alphabetically)

thanks! :)

**Comment by chutko** [comment]
1. dont bother with html/css too much. for the select, we can use default materialize select (there is no need for search inside it) and for the order switch just use a link with icon inside. i might as well create html/css in advance for you... if i can make it today, i will let you know which branch is it in

2. so the "value in the circle" will be either "money sum of contracts" or "amount of contracts" depending on what the user specified in the query builder... maybe @zufanka can propose better texts, however, just writing "sum" or "count" is not clear enough.

**Comment by chutko** [comment]
@ca1yps0 i have put html for the sorting/ordering select into the branch **fix/118** 
there might be some mistakes, i had trouble to simulate select correctly. let me know if it acts weird

**Comment by zufanka** [comment]
@ca1yps0 sorting on the count is alphabetical, not numerical

![image](https://user-images.githubusercontent.com/2411066/30189466-406c1b54-9434-11e7-9502-8b4f9e85e666.png)

**Comment by chutko** [comment]
oh, then its not just in safari, its chrome as well and others too. i have reported the same in #291

**Comment by zufanka** [comment]
@chutko no, this issue is very old and originally was something different :)

**Comment by zufanka** [comment]
I think this is solved
