### ISSUE TITLE
I can't keep only the mother CPV

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#119]
I only want to keep only the 7200000 CPV (it's a CPV on it self, and I do not want any others now)
![image](https://cloud.githubusercontent.com/assets/2411066/21296483/2b45b8ca-c56d-11e6-9dc7-1bece5c827a1.png)

but if I uncheck any of the child CPVs, the 7200000 unchecks too.
![image](https://cloud.githubusercontent.com/assets/2411066/21296486/341cd28a-c56d-11e6-8a55-6dba696c9a6a.png)

Idea:
- first click on mother checkbox checks everything (mother + children)
- second click checks only mother
- third click unchecks all

**Comment by ca1yps0** [comment]
so i solved the settings for jstree so that only the mother cpv can be selected. 
but somehow after selection when returning to previous page & after jstree _refreshSelected: the selectedCodes contains the also the children.
