### ISSUE TITLE
Implement Elvis traffic statistics

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#137]
Implement Piwik analytics on the Ember frontend

**Comment by victor-nitu** [comment]
This is blocked by the backend migration. Will happen after fixing up the deployment strategy for it.

**Comment by zufanka** [comment]
ping @georgiana-b @nightsh

**Comment by victor-nitu** [comment]
I unassigned @georgiana-b and made the issue only related to frontend. Will make the setup soon, so production environment traffic will be logged.
