### ISSUE TITLE
Filtering out red flags of corruption

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#160]
"Users will also be able to see and filter out various red flags of corruption from the network, to focus on their interests."

- frontend: design + implementation

**Comment by zufanka** [comment]
I think this is not a thing for now. It is in the milestone but so far we only have 2 possible flags (single bid and market dominance). The user will be able to filter with their eyes until we have more of them. I propose closing this.

**Comment by nightsh** [comment]
Agreed. Will close this issue, as we currently miss a lot of ingredients for it. Feel free to reopen once we get there.

**Comment by chutko** [comment]
actually, we can also have different color for every type of "red" flag and the whole lotta shit is solved
