### ISSUE TITLE
Trendline in detail view

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#161]
A trend line in the detailed view of _supplier, procurer_ and _relationships_ of:
- contracts awarded 
- sum of contracts awarded (depending on the choice of what edges/ nodes are)
- if in one year the supplier / procurer had a lot of contract with red flags, use a different color (gradient)

needs to be designed as well

**Comment by nightsh** [comment]
Temporarily blocked by tenders-exposed/elvis-backend#37

**Comment by georgiana-b** [comment]
This is no longer blocked by the backend. The `date` field has been added to the `award` object in actor details since [this commit](https://github.com/tenders-exposed/elvis-backend/pull/41/commits/13f17182b0b0b9cb551a58e33c6b57c1661cc1e1).
