### ISSUE TITLE
Company- centric networks

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#162]
Company centric networks with 2 levels of distance:

Company(ies) -> who is it working for -> other companies working in _the same markets_ as the chosen company(ies) for these institutions.

[discussion](https://talk.tenders.exposed/t/company-centric-networks/54)

**Comment by georgiana-b** [comment]
Does the "other companies working in the same markets as the chosen companies" still hold?

**Comment by zufanka** [comment]
Thanks for the observation G, no, not for now. Let's stick with the direct links only for now.

**Comment by zufanka** [comment]
@georgiana-b does this issue still serve some purpose being open?
I think not?

**Comment by georgiana-b** [comment]
I guess not, especially since we have the discourse thread now.
