### ISSUE TITLE
Options to reduce network size

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#163]
We could give the user choices before rendering network that would make it more manageable.

I imagine this coming as check-boxes in the second menu together with the edges/ nodes sizes

- don't show pairs with a weighted degree of 1 between them and no other connections within the network
- don't show procurers/companies with a weighted degree of 1 (only one contract in the whole network)

More hardcore:
- show only the largest connected component

Part of [Improved performance of network rendering](https://github.com/tenders-exposed/elvis-ember/issues/164)

**Comment by zufanka** [comment]
@nightsh @chutko @georgiana-b will we do this or do we say nay?

**Comment by georgiana-b** [comment]
Sure. The options will be even clearer when we get to the performance improvement part and start looking into the performance starts we gathered so far.

**Comment by zufanka** [comment]
@chutko @nightsh does this fit somewhere in the query builder?
Perhaps cluster together somewhere with the issue of not allowing drawing too big of a networks.

**Comment by chutko** [comment]
yep, i think it should be placed at the very end of query builder

**Comment by victor-nitu** [comment]
And... what should it adjust then? Filtering out stuff under a user defined threshold and resaving the network without the offending nodes/edges?

As I see it now, I'd do this on frontend, by filtering out weights after receiving the payload from our API. Then, send the network with filtered items back to the API to permanently store it this way.

If we only do it after the network loads, it defeats the purpose. We can do both though, but that's a separate issue.

Thoughts? Doesn't seem like a big deal.

**Comment by zufanka** [comment]
@nightsh isn't it a big deal? That is good to hear :)

I would implement a single checkbox, standardly unchecked "Only show most active companies and governments" or something like that, at the bottom of the query builder.

**Comment by chutko** [comment]
from one point of view, it is good to increase rendering performance to reduce the network on the backend. 

on the other side, after rendering, it is good to have the option to display everything if the user decides. 

something to think about ;)

**Comment by zufanka** [comment]
@nightsh @chutko @georgiana-b we won't get into this in the near future I think. Closing for now, kept the FUTURE label so we can come back to it later.
