### ISSUE TITLE
Improved performance of network rendering

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#164]
goals is a maximum of 1 minute

Related issues:
[Stop physics after stabilization](https://github.com/tenders-exposed/elvis-ember/issues/127)
[Options to reduce network size](https://github.com/tenders-exposed/elvis-ember/issues/163)

**Comment by zufanka** [comment]
@nightsh Should we close this and make an issue for each issue? :)

**Comment by zufanka** [comment]
@nightsh this can be closed, right?
We need to do testing and stuff and see what works with big networks and put them in concrete issues I think.

**Comment by chutko** [comment]
also, labels 1st milestone and 2nd milestone can be deleted. we use different milestone system now

**Comment by zufanka** [comment]
Ongoing process and this is a vague issue, closing this for now.
