### ISSUE TITLE
Clean up public folder

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#185]
- [x] `/assets/` directory is a mess (duplicated or unneeded files)
- [x] extra images in root `public` folder
- [x] look at the fonts, some of them (all?) might need to go away
- [x] tidy up a bit

**Comment by chutko** [comment]
im currently working on the cleanup concerning junk in javascript, fonts, images and styles. i will summarize my suggestions here to discuss them before actually deleting or moving something. 

### Summary
brief structure of the ember app (concerning styles, images, fonts and js libraries)
*/bower-components/*: contains all dependencies and plugins managed by _bower_. we do not touch this
*/vendor/*: contains all other dependencies and plugins NOT managed by _bower_. i would rather not put anything here. 
*/app/styles/*: all custom (in our case SASS) styles for the app 
*/node_modules/*: plugins and dependencies managed by _npm_. we do not touch this
*/public/*: this directory contains assets such as images and fonts
*/dist/*: when the app is built for deployment, the output files will reside here. so if i understand it right, all styles and js libraries included/in the pipeline get compiled into files like elvis-ember.js and elvis-ember.css. also all files from /public/ get copied here (true?)

### Suggestions for cleanup
1. remove /public/assets/jstree and include it using npm/bower. 
2. remove /public/assets/photonui and include it using npm/bower.
3. set autoloading for jstree theme (we use theme created with photonui). hint: https://www.jstree.com/api/#/?q=theme&f=$.jstree.defaults.core.themes.url
4. create separate folders for fonts and images in /public/. 
5. delete unused fonts and images: Roboto font, Materialize icons (we use font awesome), 
6. would it be a better solution to use CDN for including fonts/iconfonts? 
7. remove /vendor/ember-cli-spinkit and include it using npm/bower if possible. 
8.  is it possible to avoid puting anything into /vendor/? I mean, nowadays, every serious plugin can be included via bower/npm. its not huge, but vendor.js + vendor.css means 2 more server requests which do not have to be there
9. copy content of materializecss/_variables.scss into  /app/styles/_variables.scss - this will bring better options for setting up general behaviour of materialize 
10. how come there are Materialicons and Roboto fonts (and various other stuff) in /dist/assets? they do not appear in /public/assets, where do they come from? 
11. could /dist/assets/test-support.* files be moved to /dist/assets/tests/* ?

**Comment by chutko** [comment]
i did some cleanup. its in separate branch: 
`git checkout cleanup`

1. first three tasks (jstree+photonui) im leaving to you victor, i dont wanna mess it up. 
2. deleted roboto fonts. included fonts from CDN via <link> attribute in index.html. added TODO for including the right subset according to country 
3. installed ember-cli-spinkit https://www.npmjs.com/package/ember-cli-spinkit
however, `ember generate spinkit-<name of spinner>` outputs errors. please have a look
4. removed /vendor/ember-cli-spinkit
5. cleanup in styles/_variabless.scss. created separete file for mixins, copypasted all variables from materializecss/_variables.scss so we have good overview about variables we can use and adjust their original values if needed. 

other things from the list which are not checked, are to be answered by victor OR are only paritally finished and i would need assistance with them
