### ISSUE TITLE
Adjust content on front page (part 2)

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#189]
- [ ] the two big button links
  - [ ] Use ready-made network
  - [x] Create a new network
- [ ] Sign up for newsletter
- [x] Twitter (in footer)
- [x] Links on partners (maybe w/ some help from @zufanka?)
- [x] fix typo on footer below the Elvis logo s/spendig/spending/
- [x] remove "lorem ipsum" stuff

-----

- [ ] also a small one on "About" page: change contact email to tech@tenders.exposed

**Comment by zufanka** [comment]
@nightsh I would leave the Newsletter for now for what it is. We can add Twitter to the footer. Big buttons can be modified as suggested, what do you think  @chutko ?

**Comment by zufanka** [comment]
#331

**Comment by zufanka** [comment]
#331 < related

**Comment by chutko** [comment]
well, unless we have ready made networks, we do not need button for it. same with newsletter. so better approach is to bring a feature and spread its application across the system after it is ready. this issue is kinda obsolete now

**Comment by zufanka** [comment]
@chutko I agree. @nightsh ?

**Comment by victor-nitu** [comment]
I would close this entirely. Anyone objects?

**Comment by zufanka** [comment]
@nightsh no objections :)
