### ISSUE TITLE
Move the login form

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#195]
We need to disable the `login` route. It's messy and ugly and it shouldn't exist.

Instead, we can either use `ember-tether` to spawn the form near the login menu button, or just add it as a modal.

We can use a query string param to add it on any page. Let's say, if you load a page adding `?login` to it, it would pop up the login form.

**Comment by chutko** [comment]
also, if the user just logged in, he should stay on the same page (for example, if i was just creating a network and decided to log in before clicking "Visualise" button, i would be very unhappy to lose all my work just by logging in. same with registration.)

**Comment by nightsh** [comment]
I agree. How urgent / important would you think it is? It has a potential for being annoyingly complicated for now to fix, so I'm tempted to push it to Q3.

**Comment by chutko** [comment]
depends. if we will make public networks running, user will be able to create a network without the need to login/register. if we don't, we will need to fix it before this

**Comment by chutko** [comment]
this is part of #317. maybe we can even delete it if we agree on the flow chart in #317
