### ISSUE TITLE
Investigate Emblem.js

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#199]
http://emblemjs.com/

See if there's any missing feature. Evaluate if we can use it safely instead of plain HTML.

If it's okay, then it would be nice to allow Emblem and Handlebars templates to run side by side, so we'd avoid making a huge initial effort to translate templates.

This task is to evaluate it only, as well as the above possibility of running both Emblem and Handlebars.

**Comment by nightsh** [comment]
Will move it to "blocked" for now, waiting for some updates on [this addon](https://github.com/Vestorly/ember-cli-emblem) or on the [supported installation methods](http://emblemjs.com/installation/) for Emblem. We could unblock it around next milestone, and attempt to create an `ember-cli-emblem` addon ourselves, but I wouldn't go on such an adventure unless almost sure it's worth it :)

**Comment by victor-nitu** [comment]
Closing as this ship has sailed a long, long time ago...
