### ISSUE TITLE
Create an automatic title for networks based on the query

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#205]
**Query:**
Germany
2005-2016
CPV: 4880000 Servers; 2881000 Information Systems

If more than one CPVs are selected, just take the name of the biggest one (if possible).
Do we also know how many CPVs were chosen?

**Title suggestions:**
[flag of Germany] | 2005-2016 | Servers and 1 other
GE | 2005-2016 | Servers and 1 other

**Comment by nightsh** [comment]
Blocked by #188.
