### ISSUE TITLE
Static pages changes

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#207]
_about.hbs_ -> content **updated**
_contact.hbs_ -> content **updated**
_examples.hbs_ -> what is the difference with gallery? to be **removed**
_features.hbs_ -> to be **renamed** to _faq_ . We can put everyhing in there (what am I looking at, where is the data from, what is a network, what is a node etc)
_gallery.hbs_ -> what is the difference with examples? **To be updated** as soon as we have something to update it with.
_terms-conditions.hbs_ -> content **updated**

**Comment by chutko** [comment]
examples and gallery are meant to be the same thing. we should just agree on how will we call it :) for now, i have used examples.hbs for demonstrating how various html tags and components look. could be useful to keep this file as a guideline for further development of static pages. we just have to turn it off for the production.

**Comment by zufanka** [comment]
This has changed in the meantime. I will close this for now, if we need modifications to the static pages, new issues should be created.
