### ISSUE TITLE
Average competition in actor details is just a mock value

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#217]
Average competition in supplier details is just a mock value 1.7 for everyone.
This value should be an integer (no decimal points) and is called `median_tenderers` in the backend response.

**Comment by zufanka** [comment]
@nightsh @ca1yps0 could one of you assign this to him/herself?

**Comment by zufanka** [comment]
ping @nightsh 
could you please pick this up? I think it's low hanging
