### ISSUE TITLE
Implement usage statistics

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#225]
This is easy, just set up Piwik tracking to have some idea about how popular we are (or not) :)

**Comment by victor-nitu** [comment]
Does it make sense to set this up now, or shall we leave it to after launch day? It's a copy-paste job mostly, doable in .5 hrs together with setting up a Piwik instance. Or we could use Google Analytics. @zufanka what do you think is the appropriate timing for it?

**Comment by victor-nitu** [comment]
Ping @zufanka should we collect usage stats already?

**Comment by chutko** [comment]
not necessary right NOW, but once more people start using elvis, it could be useful. currently its better to collect usage stats just by asking people directly :) but as i'm looking at this issue, we have already spent .5 hours talking about it
