### ISSUE TITLE
create separate HTML templates for website content and network

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#235]
current state:
appicalion.hbs:

```
{{elvis-nav dropMenu=dropMenu}}

<div class="c-notifications__container">
    {{#each notifications as |notification|}}
        {{notification-message notification=notification}}
    {{/each}}
</div>
  {{outlet}}

{{partial footer}}

{{!-- ember-cli-materialize modal container --}}
{{md-modal-container}}
```

network.hbs:
`
{{outlet}}
`

there is content in application.hbs which will never be needed in the network view. like footer - we dont need it there. also, in the future i would like to wrap every common content page in a specific set of elements. therefore i suggest we completely separate these two. we already have specific template for network, but we need also one for pages (like page.hbs), where we include footer and specific markup needed for displaying pages. it will be useful now already and even more in the future.

**Comment by nightsh** [comment]
Or we can leave it on application.hbs (the footer, I mean), but mutate it into a component that takes an argument to render the template or not. We can then place that in the controllers like `footer: false` where we don't need it.

**Comment by chutko** [comment]
well i would like to have some html/css power over this aspect without need to mess with .js files - would provide some independence. i also think what i proposed is more logic than what we have now
