### ISSUE TITLE
Investigate limiting CPU load while rendering networks

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#236]
Rationale for this:

* there's a high risk of network rendering eating all the CPU, thus making the user's machine unusable while doing so. Worst case scenario, could lead to a) browser crash or b) on firefox, prompting for actions as an unresponsive script is running.
* any kind of animations, user interactions or whatever else we plan making available at that point would be barely usable

Now, there are also downsides, meaning it will render slower. Not aware of anything else right now.

If we go this path, I have found this library: https://github.com/polygonplanet/chillout

We (I) can build an ember addon around it, to smoothly integrate into the app and Ember ecosystem. 

Opinions? This is up for debate before doing **any** kind of move about it.

**Comment by zufanka** [comment]
Sounds reasonable, given that the poor unknowing people might try to render a network of 4000 nodes. Also, the library description says: "Iterate without delay if processing is fast.", so there is actually no downside to it, or am I missing something?

**Comment by chutko** [comment]
for the start, maybe setting max limit to amount of nodes to be generated would help as well

**Comment by victor-nitu** [comment]
Not a priority for now, leaving it until backend migration is finished.

**Comment by victor-nitu** [comment]
Won't do it now, will reopen if necessary.
