### ISSUE TITLE
wrong <body> class when network sidebar is closed

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#240]
there was a previous issue about this which i am unable to find anymore. the solution does not work properly yet, so i will summarize:

we need this: 
when network is displayed, body has class `body-network`. in all other cases, body has class `body-page` (or might be enough for it not to have any class). 

currently the trouble happens when network sidebar is closed: body has both classes: `body-page` AND `body-network`.

**Comment by victor-nitu** [comment]
Can this be mitigated by having more precise selectors? It's messier to deal with it on the JS side. Not impossible, just a bit more complicated.

* `body.body-page`
* `body.body-page.body-network`

**Comment by chutko** [comment]
well i have set up the selectors so they work with how the body classes are set up currently. just there is not much logic in it. logic is all i am trying to achieve

**Comment by zufanka** [comment]
ping @chutko @nightsh

**Comment by zufanka** [comment]
is this still an issue? @nightsh
