### ISSUE TITLE
Network is not rendered in the center of the window

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#247]
I know this is nitpicking, but my OCD is killing me for it!!

Here's a screenshot from another issue (ignore the sidebar, that's #246's problem):

![](https://user-images.githubusercontent.com/1579997/27656120-87b203aa-5c50-11e7-87a7-b2c409517764.png)

It used to be in the center, now you have to drag it rightwards to be able to navigate properly.

It's surely a CSS / flex thing to fix, we might keep an eye open for the easy fix I suppose it is.

**Comment by chutko** [comment]
i guess also applies only to firefox, in my chrome its centered

**Comment by nightsh** [comment]
Closing, as it somehow fixed itself.
