### ISSUE TITLE
Clustering UX improvements

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#249]
- [x] search/filter nodes
- [x] scrollable list(s)
- [x] loader animation

**Comment by chutko** [comment]
i have also some suggestions: 
- clicking on a node in the left container could make the node appear in the right container
- when holding a node above a container, the landing area should be more clear the whole container should change style. also it should be clear where in the list of other nodes will the new node land - will it land above or below other nodes? 

inspiration: https://www.uxpin.com/studio/blog/8-user-control-ui-patterns-worth-using/

btw isnt there some library which offers premade drag & drop UX?

**Comment by chutko** [comment]
btw do we use general plugin/library for displaying the loading animation? we should... there will be lots of loading everywhere. 

related to #88

**Comment by zufanka** [comment]
@chutko very good ideas! The functionality is however working for now, so @nightsh @ca1yps0 would implementing this this require a lot of time/ effort?
