### ISSUE TITLE
Style the country selector

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#250]
At the moment, chosen countries appear rather large and unstyled:

![image](https://user-images.githubusercontent.com/1579997/27905026-58709da2-6247-11e7-8d59-a44f60fe42cb.png)

This might be easier to fix by rewriting the whole styling for that.

- [ ] Fix the selected options styling
- [ ] Avoid overlapping with the elements below (range slider)

**Comment by chutko** [comment]
its beautiful now!
