### ISSUE TITLE
Refactor common entities into classes

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#251]
Alright, time to do a little cleanup. In order to keep things simple, some of the entities we're commonly encountering throughout the code could (and should) be factored into classes:

- [ ] Supplier (maybe extending a Node class?)
- [ ] Procurer (likewise)
- [ ] Relationship (edge?)
- [ ] Contract

As a bonus, this would probably make the code a bit easier to test. Definitely easier to read.

**Comment by victor-nitu** [comment]
This will take effect once we have the new backend and we can make models for things that have IDs
