### ISSUE TITLE
Bring back the nav menu on network views

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#252]
You might have noticed we don't have a navigation menu on network views anymore. So we can only go back to create a new network or whatever by altering the URL.

Well, the menu is there still, but it's hidden. This issue is following a brief discussion with @chutko. What we agreed upon is:

* put a toggle for it left to the network name
* change it to appear from the left side (so it will perfectly cover the sidebar)
* remove the top menu or reshape it to meet the above criteria

Hint: we can look into the "mobile mode" of the current menu, it might be exactly what we want.

**Comment by chutko** [comment]
solved, closing
