### ISSUE TITLE
order of loading vendor styles

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#255]
when i look into the browser inspector, many of our .scss styles are overwritten by vendor.css, which means vendor is included after our styles. that is wrong - we want to be overwriting vendor styles with our own. can we switch this order?

**Comment by nightsh** [comment]
I'll look into it 👍

**Comment by chutko** [comment]
can we please put this on higher priority? because unless solved, redundant css has to be written to make some things work
