### ISSUE TITLE
Clustering window has no scroll bar

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#265]
![image](https://user-images.githubusercontent.com/2411066/28426493-8fc5aaf4-6d73-11e7-8c09-86f50609729c.png)

Can't create more than 2 clusters and can't chose from companies further down the list

see network:
https://elvis-ember-develop.herokuapp.com/network/5970cf242dcb5627eb000009

**Comment by zufanka** [comment]
This seems to be fixed now 👍

**Comment by zufanka** [comment]
@ca1yps0 can we close this?

**Comment by zufanka** [comment]
@chutko can we close this?

**Comment by chutko** [comment]
i did not fix this, but it seems to work fine, so lets close

**Comment by chutko** [comment]
i plan to improve few UX things on clustering dialogue. but there's an issue for that
