### ISSUE TITLE
Add isOnline property

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#27]
Add a small service to check is API is online and broadcast some message to the app. Message should be visible in the frontend and API requests should be disabled with an error notification.

**Comment by nightsh** [comment]
The corresponding API route for checking its status is `/ping`, as follows:

* HTTP status 200: all fine, it's alive
* HTTP status 4xx / 5xx or anything else: something's wrong

We should display a message in the frontend if the API is offline and disable all XHR powered buttons (all buttons should check with the service if the API is online before firing a request).

This could get messy, as we don't want to make an additional GET request for `ping` every time a request is made, so we should poll the API through the service instead (one minute or so precision). Rabbit holes warning still strong though.

**Comment by victor-nitu** [comment]
Won't fo it now.
