### ISSUE TITLE
emphasise the matching phrase within results of the suggestion search select

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#271]
when user types a phrase into select's suggestion search (in query builder selects - countries and companies), the matched phrase should be highlighted within each result:

for example, if value of the search is "RD", results will have such html:
```
<div class="search-result">Amste<span class="search-phrase">rd</span>am</div>
<div class="search-result">Rotte<span class="search-phrase">rd</span>am</div>
```

**Comment by victor-nitu** [comment]
Currently blocked by OrientJS being unable to play nicely with OrientDB 3.x, which adds this functionality for us. Will wait on upstream patches.
