### ISSUE TITLE
Email validation is wrong

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#274]
It seems our email validation (frontend based) fails to recognize perfectly valid addresses. See the image:

![image](https://user-images.githubusercontent.com/1579997/28770630-91220b2c-75e8-11e7-9a25-f259836a9a4e.png)

**Comment by zufanka** [comment]
@ca1yps0 could you please pick this up?
It's a very old issue

**Comment by victor-nitu** [comment]
I cannot reproduce it anymore. Closing.
