### ISSUE TITLE
improve UX of the company select in query builder

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#278]
currently, when the select is open, there are no options displayed until user starts typing into the search. this is confusing, some people might think there are just no companies to select from. 

better solution would be a search input with suggestions. what ember component can we use for this? @nightsh

**Comment by nightsh** [comment]
I wonder, if we fire a blank request on click (i.e. empty search term), would the backend reply with anything? I can try, or maybe @georgiana-b knows the answer straight away.
Or we can preload the search term with something of our choosing. This would imply extending (not forking) the select-guru component, but it shouldn't be a big deal.
Any other ideas?
