### ISSUE TITLE
Clustering window [x] will remove clusters, window not removable

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#280]
Clustering window closing [x] will remove clusters and the window is not removable from the screen anymore.

**Comment by zufanka** [comment]
@nightsh the clusters don't disappear anymore, but I still can't click away the dialog (on production)

**Comment by georgiana-b** [comment]
Confirming:

- ❌ on the actor label doesn't remove the actor
- 🗑 doesn't remove the cluster
- ❌ on the clustering window doesn't remove the window

Basically, once you start clustering there is  no going back! 😨

Browser: Chromium Version 60.0.3112.113 (openSUSE Build) (64-bit)

**Comment by georgiana-b** [comment]
I just tried clustering and they both worked fine after a hard refresh.

**Comment by zufanka** [comment]
Still issue in Firefox (54.0)

**Comment by victor-nitu** [comment]
@zufanka Still an issue? Does it print anything in the js console?

**Comment by zufanka** [comment]
@nightsh this is resolved (tested on develop)

**Comment by zufanka** [comment]
@nightsh I had this issue on develop briefly today again, page refresh had fixed it tho

**Comment by zufanka** [comment]
@nightsh this is still an issue if trying to cluster on a [network that already has clusters](https://elvis-ember-develop.herokuapp.com/network/59cba00b2dcb565b0300008d) !!

**Comment by victor-nitu** [comment]
That's a good catch @zufanka!

**Comment by zufanka** [comment]
![image](https://user-images.githubusercontent.com/2411066/30920166-a1ca9884-a3a3-11e7-960e-5f445edf8dbd.png)

**Comment by victor-nitu** [comment]
Recording this network ID here as well, as it reproduces the problem: `59ce470d2dcb563afb000012`
