### ISSUE TITLE
Show red flags on the network

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#281]
We currently don't have a way to show the red flags in the network graph visualisation. We need to do it :)

**Comment by nightsh** [comment]
here's an image showing an approximate way of integrating unicode symbols on edges 
![image](https://user-images.githubusercontent.com/1579997/29240870-28a0693a-7f76-11e7-861f-a28b999a744a.png)

**Comment by nightsh** [comment]
Also on nodes, we need them on nodes. Labels might save us again, just glue a newline and a unicode flag to the original node label. We could also use multifont labels, if performance impact is decent: http://visjs.org/examples/network/labels/labelMultifont.html

**Comment by nightsh** [comment]
Pinging @chutko, I think we need your mind's eye for this one :-)

**Comment by chutko** [comment]
here are few quick ideas. 

![elvis--visualisation-red-flags](https://user-images.githubusercontent.com/4135015/29603063-fcc0dd8e-87e2-11e7-97a2-7b25bedf1386.png)

to summarize, we have red flags either on edges or nodes. they can have various thickness/sizes. an on/off button for showing/hiding all the network's red flags might be useful.

**for nodes**, the best solution is probably to display red flag(s) near the node name label and also style the label a bit as it is on the image for node _"BFE Studio und Medien Systeme GmbH"_

**for edges**, an icon in the middle of the edge with background is enough as it is on the link victor provided

also, there is a question of **icon** - flag icon is nice, but the one provided by font awesome takes more space and has to have at least 13px size to look like flag. exclamation mark (in the attached image) is more functional in this matter but its not a flag which puts it out of context :) 
i've designed something simpler - an html/css component: http://fiddlesalad.com/css/elvis-red-flag/ 
...is it possible to use that?

**Comment by chutko** [comment]
posting an update on red flags. let me know what you think

![elvis--visualisation-red-flags](https://user-images.githubusercontent.com/4135015/29611173-dd23d110-87fc-11e7-9bd1-ec86ef87e82a.png)

**Comment by chutko** [comment]
sending an update. the change is - node red flags are centered under the node and the red flags are bordered inside a rounded rectangle. 
![elvis--visualisation-red-flags2](https://user-images.githubusercontent.com/4135015/29918837-4db37926-8e47-11e7-81a9-c7762c47c10e.png)

also, lets make part of this issue (or a new related issue) following:
- double click on a node should trigger details dialogue.
- single click on a node will zoom the node to the center and highlights the node's subnetwork (its neighbours and edges):
![elvis--subnetwork](https://user-images.githubusercontent.com/4135015/29918896-89a9e2c6-8e47-11e7-8799-eecd8de2498a.jpg)

**Comment by chutko** [comment]
i consider this one better:
![elvis--visualisation-red-flags3](https://user-images.githubusercontent.com/4135015/29923561-4e1a936e-8e5a-11e7-9c3f-b3759208963d.png)

is it doable?

**Comment by nightsh** [comment]
No.

**Comment by chutko** [comment]
so what is?

**Comment by nightsh** [comment]
I'll look a bit into it tomorrow afternoon and see how close I can get to it. But there are some vis.js limitations involved. Wish me luck :neckbeard:

**Comment by chutko** [comment]
@ca1yps0 said there might be possibility to have custom HTML for each node's label. if that is true the above visual should not be a problem - we just add another container for the flags and other stuff

**Comment by nightsh** [comment]
a. node labels are doable, although they might get a bit on the heavy side, we need to performance test some stuff before
b. edge labels, on the other hand, are a bit weird due to the tilted border and vertical flags. But I'll give it a shot soon.

I also don't know how can we style the things yet, I suppose we get html labels then go on with our own classes, right?

This would be quite pretty if vis.js plays along. However, we need to keep an eye on performance, as it burdens the whole rendering a bit. I don't know much about the canvas generation and html-to-canvas translation that's being made there, that's why I'll have to try it out first. The visjs source code doing these things is pure wizardry for me now.

BTW, are those edges flags vertical or tilted? My eyes are playing tricks.

**Comment by chutko** [comment]
> BTW, are those edges flags vertical or tilted? My eyes are playing tricks.

the whole flags container is rotated, so the flags go with it. but whatever is easier to do will be fine.
