### ISSUE TITLE
selecting CPV upper branch does not select the lower branches

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#284]
If I click on "Petroleum products, fuel, electricity ..." it does not select "Fuels" automatically.

![image](https://user-images.githubusercontent.com/2411066/29556289-a78ba046-8725-11e7-9cd9-9bfd61643d3d.png)

**Comment by chutko** [comment]
this could be also done with css - if a parent node has class `.selected`, we can display "checked" icon also on its children

**Comment by chutko** [comment]
i gave it some thought. indicator of the selected CPV category is html attribute `aria-selected="true/false"`

**here is desired behavior:**
1. if user selects a cpv category, all its children should automatically be selected.

2. after selecting a parent and all its children, if one children is deselected, the parent should not be selected anymore.
