### ISSUE TITLE
sidebar - sorting by count displays wrong order

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#291]
in the sidebar, when sorting lists of nodes or relationships by count, the lists display in wrong order
![elvis--sidebar-sort by count](https://user-images.githubusercontent.com/4135015/30102922-5f5d01d4-92f1-11e7-86c1-c73b24e626af.png)

it seems the sort algorithm is sorting _String_ instead of _Number_

**Comment by zufanka** [comment]
@ca1yps0 could you please have a quick look at this? Thank you!

**Comment by zufanka** [comment]
@ca1yps0 could you please solve this this week?

**Comment by zufanka** [comment]
@ca1yps0 thanks!
Who has to review this?
It is not pushed on the develop yet that I can see namely
