### ISSUE TITLE
CPV tree loads before applying styles to it

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#294]
in the query builder, when i make action which loads the CPV tree for the first time, it always takes a short while to load all the styles so the user sees unstyled CPV tree just with names and nothing else. 

if it is possible, we should display CPV tree after an event is fired when all necessary styles have been loaded and applied

**Comment by zufanka** [comment]
@nightsh @ca1yps0 ?

**Comment by zufanka** [comment]
not sure this is still an issue, think not.
