### ISSUE TITLE
disallow Query Builder submit button unless all data is filled

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#295]
the query builder "Visualise!" button at the bottom can be pushed event if no Country/Company (step 1) was selected and after that if no CPV code (step 3) was selected. 

until all required fields are filled, the button should be like this:
`<button type="submit" disabled="disabled">Visualise</button>`

**Comment by zufanka** [comment]
@nightsh @ca1yps0 ?

**Comment by zufanka** [comment]
ping @nightsh
