### ISSUE TITLE
Do not show network editing controls when there are no appropriate permissions

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#300]
Right now we see clustering and network name editing controls on all networks. Even if they're not ours to modify.

We need to fix this and only allow owners to see such things. Backend will reject the action anyway, so we just have to show them conditionally.

**Comment by zufanka** [comment]
I think this is important, more so on the new backend

**Comment by zufanka** [comment]
@nightsh will double check this

**Comment by victor-nitu** [comment]
Needs to be done on clustering as well. When we get to touch that part, as we're about to anyway.
