### ISSUE TITLE
Create 404 pages on the Ember app

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#301]
Just make some thing that gets loaded whenever a 404 gets hit. @chutko will take it from there.

**Comment by chutko** [comment]
maybe we could have a list of addresses which redirect to 404. so far i have these in mind:
- [domain]/*
- [domain]/network/*

where "*" is anything except of existing routes and existing network IDs

**Comment by victor-nitu** [comment]
Got it into the issues pipeline, will tackle it shortly.
