### ISSUE TITLE
Put the right values in the competition

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#303]
These are always 1.7 in the detail view and 1.1 in the small modal on the network.

![image](https://user-images.githubusercontent.com/2411066/30697396-2543a7f6-9edf-11e7-9a2f-235a1f0b104f.png)

![image](https://user-images.githubusercontent.com/2411066/30697405-2bd104d8-9edf-11e7-9770-cdf16259299a.png)

**Comment by zufanka** [comment]
@nightsh @ca1yps0 could one of you have a look please? There should be a backend response containing this.

**Comment by zufanka** [comment]
@georgiana-b will add this to the payload

**Comment by georgiana-b** [comment]
@zufanka This was already present in the actor details payload as `median_tenderers` and as a red flag.

I noticed that on the backend the flag is being calculated only for suppliers. Does it make sense to show `average_competition` for procurers nodes and in procurer details?

**Comment by zufanka** [comment]
@georgiana-b 
> Does it make sense to show average_competition for procurers nodes and in procurer details?

yes it does! Governments can tailor tenders. That would mean that the median bids on their tenders would be 1 too.

**Comment by georgiana-b** [comment]
The backend side of things was solved in tenders-exposed/elvis-backend#69. Please see the description of that PR for what has changed in the payload.
