### ISSUE TITLE
Sidebar not updating after clustering and more weirdness

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#304]
After applying clustering and trying to focus on the node from the sidebar

![image](https://user-images.githubusercontent.com/2411066/30843366-04493a2c-a289-11e7-8bab-16827996b69a.png)

The focus will go to the old position of the node, not the new one.

See this [example network](https://elvis-ember-develop.herokuapp.com/network/59c9de932dcb565b03000035/suppliers)

**Comment by zufanka** [comment]
@nightsh @ca1yps0 

[Germany, Agricultural machinery](http://tenders.exposed/network/59de219c2dcb561714000005/suppliers)
After clustering, network comes out all weird
![image](https://user-images.githubusercontent.com/2411066/31444308-28568342-ae9c-11e7-888b-0aa81fa385b5.png)

need to turn on physics to make it draw normally.

![image](https://user-images.githubusercontent.com/2411066/31444567-de4daf72-ae9c-11e7-96ec-0e0b53fae3f7.png)

Then, the side bar is not uploaded and points to the previous position of the node
![image](https://user-images.githubusercontent.com/2411066/31444560-d5863990-ae9c-11e7-8f00-9ba23c1398f4.png)

when refreshing, sidebar is gone and there is no info in the infobox when clicking on a node
![image](https://user-images.githubusercontent.com/2411066/31448527-f13bffbe-aea4-11e7-86a0-69069950c00f.png)

**Comment by zufanka** [comment]
@nightsh is this a cadidate for a HOTbug?

**Comment by victor-nitu** [comment]
@ca1yps0 would it help if we do this sequence:

* click the clustering modal close button
* deactivate the network service
* send the payload, receive a response (stuff that already happens)
* after response / redraw, activate the network service

Could it also be that the computed properties are not getting... computed?

**Comment by zufanka** [comment]
@nightsh update! After you try to cluster again, the sidebar is back, but you can definitely not cluster anymore

![image](https://user-images.githubusercontent.com/2411066/31855084-a47076e0-b6a3-11e7-93ed-44c1a84ee041.png)

[network](https://elvis-ember-develop.herokuapp.com/network/59eb99252dcb5621180000b1/suppliers)

**Comment by chutko** [comment]
@nightsh although this issue rather concerns what happens after closing the clustering dialogue:

be aware that i've made a big commit into files concerning clustering yesterday (the pull request didnt pass yet, maybe its good to merge)
