### ISSUE TITLE
Clustering dialog search not taking '-' and '+', zooming instead

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#305]
If I am searching for a company that has a '-' in the name, the clustering dialog would not take it, but the network on the background will zoom out. The same issue with '+' .

**Comment by chutko** [comment]
same problem in different context is also described in #243. 
i've also proposed a simple solution. marking as low hanging

**Comment by zufanka** [comment]
@ca1yps0 could you please pick this up this week?

**Comment by victor-nitu** [comment]
It was fixed by this commit: e9f5b5b3baced48edd6b14b7fe9c761376d97b11
