### ISSUE TITLE
Network list fails to render on HTTP status 304 from the API (Was: Networks no longers saved in "My projects")

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#307]
_(Update: the ember-data side needs to make sure it also treats some 3xx HTTP status codes as valid, instead of only accepting 200s)_

I have been creating networks left and right on the dataharvest account. Yet none of them are being saved anymore.
(production and develop)

(possibly backend issue @georgiana-b ?)

**Comment by georgiana-b** [comment]
I just made one and it was saved and displayed in "My Projects" but the details say it was created `14 days ago` which is wrong. I noticed I don't send `created_at` in the payload so `14 days ago` is a mock value. 
Can you check if the networks you refer to are saved but shown with the wrong date?

**Comment by georgiana-b** [comment]
Oh wait, after hard refresh I just get "Loading Network" on `http://tenders.exposed/network/list` even though the response from backend arrives and is correct.

**Comment by victor-nitu** [comment]
What's your user, @georgiana-b? Also, can you possibly spot any difference between the payload that renders the list and the one that doesn't?

**Comment by georgiana-b** [comment]
The first time I request "My projects" page it is loaded with networks but after I refresh/reload the page just keeps loading.  
I just converted the payloads when it is working and when it isn't into Python dicts and compared them but they are the same.
The only difference is that after the first request the status is `304 - Not Modified` instead of `200`.

**Comment by victor-nitu** [comment]
Ah indeed! I guess HTTP suggests 304 in this case indeed, and the issue should be somewhere around the data adapter in Ember. I'm looking into it now, just grepping by hardcoded "200"s in the code base for a first try 😝 
Thanks for demystifying this, I didn't realise the status code is different. It makes perfect sense, I'll change the title and description of the issue.

**Comment by victor-nitu** [comment]
Still didn't get to look into it. Marking it as priority, as it breaks functionality.

**Comment by georgiana-b** [comment]
This issue is ancient and it was solved somewhere along the line. This works now so Ii'll close this.
