### ISSUE TITLE
Design of clustered nodes

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#309]
problem: 
1. in the sidebar, there is no specific design for clustered nodes
2. in the network, clustered nodes use [font awesome icon](http://fontawesome.io/icon/users/)

i would like to unite clustered node's design to look like this:
![elvis--clustered-node](https://user-images.githubusercontent.com/4135015/30954470-9850f0f4-a430-11e7-9b53-1a166afdfdd1.png)

questions for @nightsh and @ca1yps0 :
1. to make special style for clustered node in the sidebar is not a problem. is there a specific class to clustered nodes displayd in the sidebar?
2. what can we do to achieve this look in the network?

**Comment by zufanka** [comment]
@chutko will we keep it like this
![image](https://user-images.githubusercontent.com/2411066/31443411-acadf466-ae99-11e7-8e9e-4c6bdfb02ad3.png)

for now or shall we go ahead with implementing this?

**Comment by chutko** [comment]
we agreed that the clustered node indicator should be rather obscure. but it should be there. 

maybe we could just use a simple icon or circle to demonstrate this is a cluster (dont even have to display how many are there in the cluster)

![elvis--clustered-node-v2](https://user-images.githubusercontent.com/4135015/31494254-c3ce85a2-af52-11e7-946f-6a00b92a06d7.png)

i think to use a circle will be easier to implement and i also like it more visually. icon inside label might make another problems with implementation.

**Comment by zufanka** [comment]
I think both solutions are fine, pick whichever is easier :)
