### ISSUE TITLE
Query for relationship details misses one part of the relationship

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#316]
For example in [this relationship details page](https://elvis-ember-staging.herokuapp.com/network/59d29bb72dcb563afb00003c/relationships/24989-1102500) the `procuring_entities` parameter is not present in the `query` of the request.

So, for relationship details you just make a request for either `api/v1/suppliers_details` or `api/v1/procuring_entities_details` and give both the `"suppliers": [x_slug_id]` and `"procuring_entities": [x_slug_id]` of the parts involved.

**Comment by zufanka** [comment]
@ca1yps0 could you please pick this up this week?
