### ISSUE TITLE
Make clustered nodes look like any other nodes

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#323]
Now we have an icon for clustered nodes. This does not make sense actually, as the clustered nodes are the same company.
The clustered node should therefore be the same as any other nodes. They will keep the number of nodes in the clusters after the name of the node. The size will be dependent on the sum or count of the contracts.

**Comment by zufanka** [comment]
@nightsh @ca1yps0 ?

**Comment by chutko** [comment]
i think this is low hanging as soon as we agree on the solution. 
btw quite same issue as #309
