### ISSUE TITLE
register does not work (for emails that are already registered)

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#325]
![image](https://user-images.githubusercontent.com/2411066/31286473-863de298-aabe-11e7-97bb-67a9d7d74564.png)

clicking send does not do anything .. if the email is known to the system I guess.
With other email it worked.

#fuckingwithauthentication

**Comment by victor-nitu** [comment]
@georgiana-b I assigned you too to this, as it's part of the "things to keep in mind when designing the authentication backend" series :)

Are we going to fix this one, or leave it to rot in here until we change the backend?

**Comment by zufanka** [comment]
ping @georgiana-b 
still needs to be open?

**Comment by zufanka** [comment]
new authentication fixes this I would believe? @nightsh ?

**Comment by georgiana-b** [comment]
Well of course it doesn't. The problem was actually that it didn't give any significant message like "User already exists". These days it does show the correct message and it will also look pretty after #406 so I'll close this.
