### ISSUE TITLE
My Projects page: date

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#327]
![image](https://user-images.githubusercontent.com/2411066/31287924-423bfd1e-aac3-11e7-9653-3b18c158b8ad.png)

If the network does not have a name, it is undistinguishable from the others.
Until the thumbnails are there, can we replace the "14 days ago" with some real data?

**Comment by victor-nitu** [comment]
Good point. While this is a well known issue, it has been left untouched for too long. Time to do something about it.
@ca1yps0, are you taking it or I will? It's low hanging.

**Comment by chutko** [comment]
just to let you know, giving a design boost up to this page is on my list

**Comment by victor-nitu** [comment]
@chutko so you wanna block this until revamping the design? It's fine by me, just let us know so we won't spend time on the current page design if we'll be having a new one soon.

**Comment by chutko** [comment]
i want to keep the displayed data on this page basically the same. just was thinking about displaying the list linear ordered by date. so i would propose you guys fix the data issues (if it is an easy task) and i will redesign after (or during, on /examples page)

**Comment by zufanka** [comment]
new projects page. closing this one
