### ISSUE TITLE
Users not logged in should not be able to go to query builder

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#331]
Could we change this button

![image](https://user-images.githubusercontent.com/2411066/31434812-c9151574-ae7d-11e7-8f72-29e6b9a6f416.png)

To "Create an account" if the user is not logged in?

and make this not visible / clickable also if the user is not logged in
![image](https://user-images.githubusercontent.com/2411066/31435007-6964edce-ae7e-11e7-8b6e-f41176084ddd.png)

**Comment by victor-nitu** [comment]
The initial idea was to tease the user a bit, see what are the options inthe QB. We should probably let the user see and manipulat the QB, and be a bit inventive about telling them to register before they spend too much time pressing buttons and crafting the perfect query.

Based on the results so far, I'm gonna tag @chutko here for being my fav UX person to ask. Lead my editor, captain, what shall I code? :skull_and_crossbones:

**Comment by chutko** [comment]
@nightsh 
what @zufanka wrote above is what we both agreed on. its the easiest and least annoying temporary solution until we have functionality for public networks ready

**Comment by victor-nitu** [comment]
Alrighty, I'll open a PR shortly with these modifications.

**Comment by victor-nitu** [comment]
The "New Visualization" link is still shown if you're not logged in, but dead. We need to direct visitors to the "login" or "register" page, or just leave it out completely.

**Comment by zufanka** [comment]
@nightsh we can leave it out completely if that is not too much hassle

**Comment by victor-nitu** [comment]
Nah, it's a few minutes fix. Will nail it when I'll be around that app section, which will happen very soon.

**Comment by chutko** [comment]
i am fixing it.

**Comment by chutko** [comment]
fixed via #386
