### ISSUE TITLE
Empty labels (company names) will not dissappear after zoom out

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#337]
![image](https://user-images.githubusercontent.com/2411066/31819313-72a22882-b59c-11e7-8ef0-dcce7251375c.png)

[example](https://elvis-ember-develop.herokuapp.com/network/59e9df882dcb56211800002d)

**Comment by zufanka** [comment]
@ca1yps0 this is still not fixed!

**Comment by georgiana-b** [comment]
Is this related to #428 @zufanka ?

**Comment by victor-nitu** [comment]
@ca1yps0 was this fixed? Can you review and close / update the issue please?

**Comment by zufanka** [comment]
@ca1yps0 ?
