### ISSUE TITLE
Clustering happens after network stabilization

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#338]
As expressed in #304, part of the weirdness there is that after clustering the network's layout is all messed up.

![](https://user-images.githubusercontent.com/2411066/31444308-28568342-ae9c-11e7-888b-0aa81fa385b5.png)

This is very likely due to the fact that the network:

* loads
* does physics simulation
* finished simulation iterations
* clusters
* renders

We need to cluster before doing any physics. Somehow.
For this task, the use of forks is allowed.

**Comment by zufanka** [comment]
is this the same as https://github.com/tenders-exposed/elvis-ember/issues/365 ?

**Comment by victor-nitu** [comment]
No, not really, but fixing that one would likely fix this as well.
