### ISSUE TITLE
Create modal component with materialize modal

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#340]
we are using several modal windows (clustering, embed, login etc), but we are not using unified HTML/CSS markup to display them. all modals should use the same core functionality. 

in ember-cli-materialize there is a modal window component we can use. 
http://mikeworks-ui.herokuapp.com/oss/ember-cli-materialize

so the way i imagine how to use this functionality:
components/modal.hbs
```
<div class="modal {{class}}">
 [blah blah, other modal markup]
</div>
```
account/login.hbs
```
{extends modal} //this wraps the following code into modal markup
{class="login-modal", title="Login to your account"} // from the inheriting template, we need to be able to specify few attributes of the modal
<h1>This is some markup which will appear inside modal
```

**Comment by chutko** [comment]
can be closed i guess, right @nightsh? i just tested the component when styling new modal in #376

**Comment by chutko** [comment]
update: closing the modal by clicking the close button, hitting ESC key or clicking on the modal backdrop does not work - this works on the component demo page, but not in elvis: 
https://mike-north.github.io/ember-cli-materialize/#/modal

**Comment by victor-nitu** [comment]
Won't fix.
