### ISSUE TITLE
Connection between network zoom and export preview zoom is confusing

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#341]
Currently in the preview I can zoom *out* only a few orders of magnitude of the network zoom and I can't zoom *in* more than the network zoom.
If I want to zoom more, I have to close the preview, zoom the network then open back the preview. 

The fact that preview zooming depends on network zooming is not intuitive and without it using the preview can be hard because the nodes are too small.

I think removing the preview zoom completely would be less confusing. This way people will know that they have to zoom in and out on the network.

Other more sophisticated solutions:
- make an independent network in the preview that can be zoomed in and out without any effect on the outer network
- make the preview just "a window" on the outer network so that in the preview people interact directly with the network itself

This is an enhancement so no rush about it but I think it would improve the user experience a lot.

**Comment by zufanka** [comment]
@georgiana-b isn't this related to the old version? In the crop, this is not an issue I think

**Comment by zufanka** [comment]
not applicable anymore
