### ISSUE TITLE
Component displaying collection of networks

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#352]
we are displaying collection of networks both on My Projects page and in the near future, on the Selected Public Networks page (Gallery). 

i would like to design a component displaying list of networks. based on html markup and css classes, each item (network) in the list can be rich full of data or just very simple according to the needs of specific view. here are basic parts i would like to include in this component:
- network name, description, image snapshot
- last edited date
- network formula (country, year range, companies, CPVs)
- network complexity (number or word expressing rendering difficulty)
- control buttons (delete button and others)

here is a glimpse of how it might look:
![elvis--mynetworks2](https://user-images.githubusercontent.com/4135015/32103670-bdae0b36-bb21-11e7-9678-2d1c780ff549.jpg)

**Comment by zufanka** [comment]
@chutko thank you! I am sorry I am a bit late to the party, but I thought about it better.

It looks good content wise, however I think the rows it's a bit big for the purpose: just quickly find a network I was working on.  Also: you want to know when you created the network and when you accessed it for last. The "yesterday" is not enough. The list should also be sorted on the "last accessed" date.

I would therefore opt for a rigorously tabular overview with rows and columns which you can easily sort on date and search. Perhaps the thumbnails are also not really needed? 

I would also add a column to the table that would indicate whether there are joined nodes in the network or whether it is a virgin network. That means that you have already worked on the network and not just created it and don't want to do more with it.

Shall we have a brainstorm on this in the upcoming days?

Most of the networks will be I think of just one country, but it is good to have possibilities for more.

**Comment by chutko** [comment]
@zufanka this one is the most richest view of the project list you can achieve. but i tried to make it so you can remove any of those subcomponents (like years, description or thumbnails) and it would still look fine and not fall apart. 

so maybe, for the list of Public Networks this complex view is fine. and yes, for My Projects, these things you said are totally in place. 

I would like now to continue solving Public Networks page and My Projects page in separate issues

**Comment by zufanka** [comment]
@chutko updates on this?

**Comment by chutko** [comment]
i will now implement this into MyProjects page as it is more functional than what we have currently. further improvements will follow based on discussion

**Comment by chutko** [comment]
im closing this one. applying this component to specific templates will take place in different issues
