### ISSUE TITLE
Unify the terminology

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#355]
It's not clear what they are always. A more familiar name would be preferable.

Suggestion:
procurers -> government
suppliers -> companies
relationships -> contracts / tenders

clustering -> merging
"New visualization" -> "Create new network"

![image](https://user-images.githubusercontent.com/2411066/32437858-eab890f0-c2e8-11e7-9515-1777fe0a198b.png)

![image](https://user-images.githubusercontent.com/2411066/32437867-f42f5218-c2e8-11e7-8b75-56daa724a3ff.png)

![image](https://user-images.githubusercontent.com/2411066/32996474-8bfaefd6-cd83-11e7-99c7-30b5cf514307.png)

**Comment by chutko** [comment]
also, small thing but reasonable: the order of the actors should be the same everywhere - first governments, then companies, then contracts

**Comment by zufanka** [comment]
@nightsh @ca1yps0 @georgiana-b more ideas on this?

**Comment by zufanka** [comment]
![image](https://user-images.githubusercontent.com/2411066/34258586-cc8ea97c-e65e-11e7-848d-802703e7cf81.png)

This needs to be the same as the one above !
![image](https://user-images.githubusercontent.com/2411066/34258590-d3284a40-e65e-11e7-89a5-4d2bf9e38096.png)

**Comment by zufanka** [comment]
![image](https://user-images.githubusercontent.com/2411066/34529486-7bf9e708-f0ac-11e7-8204-cbe5f9d9893d.png)

Found one! :)

**Comment by zufanka** [comment]
this one is also off
(`tenders` and `relationships`)

![image](https://user-images.githubusercontent.com/2411066/34529614-e15e4422-f0ac-11e7-8dd3-27dfcb2d4c51.png)

**Comment by georgiana-b** [comment]
@zufanka I think calling the median number of bidders `averageCompetition` makes people think this is a mean not a median. Although the word `average` is easier to grasp at first I think it creates a wrong way to think about this value that will become confusing once people learn it is actually a median.

Thus I propose we call it `medianCompetition` or something neutral like `overallCompetition` or even just `competition` and then in a info tooltip we explain what it really is. I'm sure there are people who never heard of median but they will learn  once and then become used to it as we use it.

**Comment by zufanka** [comment]
"Average" is an umbrella term for mean, median and mode. Different types of data and data distributions require different average to be used. From a statistical point of view, median is the appropriate average type to use for the competition data.

We can explain in the tooltip that we calculate median, sure, but I would propose we keep it as average competition and not over think it.

What do you think @georgiana-b ?

**Comment by georgiana-b** [comment]
When I did user testing with an economist she said

> You know average and median are not the same thing, right? 

So I think those who know what median is will be ok with using `median` and those who don't will learn what it is.
If we use `average` those who know what median is will be slightly bugged and those who don't will be confused when they look it up and discover it's different from average which is usually used for mean.

**Comment by georgiana-b** [comment]
Although I do agree that `averageCompetition` has a nicer ring to it 😄
I changed it to `medianCompetition` in the backend just to be accurate but feel free to do as you wish in the frontend.

**Comment by zufanka** [comment]
As I said, 'average' is an umbrella term, so we are accurate anyway :)
But sure, feel free to name it what you wish!
