### ISSUE TITLE
rethinking and redesigning Detail view

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#356]
the Detail (procurer/supplier/relationship/contract) modal is confusing and user can get lost easily in it. deserves overthinking and different visual approach. for now, we are collecting ideas and minor issues we are aware of from user interviews. in the next weeks, i would like to start designing and 

**ideas**
- bordering the Detail view modal, separating it from the sidebar
- dividing data into sections
- more unified and structured data
- sortable and filtrable tables of contracts
- linking to external databases from detail view

**bugs from user interviews:**
- "why there are 0.00€ contract value everywhere?" - if there are data missing, there should be N/A label, not 0.00 €
- timeline graph - "why are all contracts in the december?" - can this be bug? or just coincidence?
- it seems like in one network the "count" number inside circle near node in the sidebar is the same number as "data missing %" when opening detail view
- user chose year reange 2007-2014, but in the detail view, 1994-2014 is displayed
- contract detail view: suppliers in the list are not clickable

@nightsh @ca1yps0 please speak your mind about what the problems with above mentioned bugs can be

**Comment by zufanka** [comment]
ping @nightsh @ca1yps0

**Comment by zufanka** [comment]
This has been redesigned. Templates are ready to be implemented
