### ISSUE TITLE
Truncate long network labels

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#358]
Currently, long labels are displayed as they are, which is disturbing for really long names.

The task is to implement truncation of long names at a given number of characters. Ideally this would be done in our `vis` fork, but otherwise we could truncate them in the network service if this takes too long.

Bonus points if we could display the full name on hovering the truncated label.

**Comment by chutko** [comment]
also, our vis.js fork should be ready if the label is too long - it should split to multiple lines. according to vis.js documentation, this is possible by adding `\n` directly into the label string. 
example:
we have a node named `Lazy dog jumps over the river` which is a string 29 characters long. 
if we want to limit each line to 15 characters, we need a function which runs loop over the string and adds `\n` every 15 characters: `Lazy dog jumps \nover the river`

**Comment by victor-nitu** [comment]
@zufanka what do you think? Truncate them and rely on info box for showing the full name, as a first step?

**Comment by zufanka** [comment]
@nightsh that sounds good to me!
