### ISSUE TITLE
Saving networks

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#360]
**Problem:** currently, if the user is logged in, every network he creates is automatically saved. this creates mess in the My Projects page and discourages user from reusing networks he has.

**Solution:**  networks will not be saved automatically anymore. user will have to save them manually. the goal of this issue is to discuss possible scenarios this brings to the user and specify further steps to make this whole idea working.  

so far, we know about these scenarios:
- we need to add Save Network button to the network view
- by saving a network, user should also specify the name
- prompt the user to save or log in/register if he tries to leave unsaved network. this has to be smoothly done in a modal if the user decides to register and save the network. 
- prompt the user to log in/register if he tries to use features which are for registered users only
- mark visually (make transparent, add text tooltip) to the actions/features which are for registered users only

**Comment by zufanka** [comment]
![image](https://user-images.githubusercontent.com/2411066/32554301-9fc1113c-c499-11e7-8f7d-e7883d69f995.png)

See the diagram above.

We need to be able to validate whether a network is saved. My proposal (perhaps not super sophisticated, but easy I believe):
- default network name is an empty string
- user needs to specify a name to the network once s/he saves it. The name has to be minimum of 3 (arbitrary) characters, but the string can not be empty
- if the name of network is an empty string = not saved network

Therefore, we should also remove the possibility of naming the network on the sidebar. It is nevertheless not needed anymore if the networks are not going to be saved automatically. We could use the space to put in the query the user is working with.

**Comment by zufanka** [comment]
@chutko anything you want to add?

**Comment by chutko** [comment]
not really right now, i will think how will all this affect the UI - a Save button needs to be added somewhere, sidebar settings adjusted/removed, network query displayed, notification and prompt modals designed. many factors to think about

**Comment by zufanka** [comment]
@chutko any deeper thoughts on this? :)
