### ISSUE TITLE
Disable automatically stopping physics on networks

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#365]
As the title says. Stopping physics before laying out the network renders it in awful positions:

![image](https://user-images.githubusercontent.com/1579997/32995088-8319bf10-cd78-11e7-9057-0736b529d399.png)

**Comment by zufanka** [comment]
is this the same as https://github.com/tenders-exposed/elvis-ember/issues/338 ?

**Comment by victor-nitu** [comment]
No, but if will likely fix that one too.
