### ISSUE TITLE
Contracts not visible

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#366]
![image](https://user-images.githubusercontent.com/2411066/32996149-4d348004-cd7f-11e7-8010-54edc0947a2c.png)
https://tenders.exposed/network/5a11fee12dcb567ce0000041/suppliers/1110586

or do we wait for the new backend to fix this?

**Comment by victor-nitu** [comment]
![image](https://user-images.githubusercontent.com/1579997/33070622-54ea3972-cec1-11e7-8278-1cdd44592117.png)

This can be safely closed now.
