### ISSUE TITLE
Sort sidebar automatically ascending on sum or count

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#368]
![image](https://user-images.githubusercontent.com/2411066/32996551-68b115fe-cd84-11e7-8ef3-4fdae8c0e0c0.png)

**Comment by victor-nitu** [comment]
An mentioned by @chutko in #383:

> also, remove "Sort By" from the sidebar select. if it is sorted by name by default, make this value selected

**Comment by zufanka** [comment]
fixed
