### ISSUE TITLE
Make the nodes of bigger values bigger

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#369]
Node sizes look now very much the same even if the difference is big. The difference should be very well visible from the largest zoomed out level.

![image](https://user-images.githubusercontent.com/2411066/32996590-e26fef64-cd84-11e7-8484-08a4348e3dba.png)

https://tenders.exposed/network/5a120a5e2dcb567ce0000045/suppliers

**Comment by victor-nitu** [comment]
if we add more elements to the network, it's going to look too crowded.

My suggestion is to tweak min/max node zoom, according to this: http://visjs.org/docs/network/nodes.html (see "scaling" section, click to expand to options)

**Comment by zufanka** [comment]
What do you mean more elements @nightsh ?
I mean that the scaling should be different. Bigger values should lead to bigger nodes, eg:

![image](https://user-images.githubusercontent.com/2411066/33012716-0c022858-cde2-11e7-944e-9a10579e2121.png)

I changed the name of the issue, perhaps it was unclear :)

**Comment by chutko** [comment]
the range of the node values can go 0-100 or 0-10. still i think we should maintain the size to be linear to the node value. otherwise people will not realize how big some company really is. 

we need some minimum node size ofc, so even the tiniest values do not get lost in the network. however, im not concerned about really big nodes making visual problems. if there is a huge node, it will be alone in most cases. and the initial network zoom should adjust so the network fits in the viewport. 

if somebody can give me an extreme example which could mess up the network this way, it will help

**Comment by zufanka** [comment]
@georgiana-b do you think it makes sense ta calculate and hard code buckets for node sizes for the actual data we have?

**Comment by zufanka** [comment]
I will calculate buckets from the data once G imports them

**Comment by georgiana-b** [comment]
> @georgiana-b do you think it makes sense ta calculate and hard code buckets for node sizes for the actual data we have?

Sorry but I don't understand what you mean by "buckets for node sizes".

**Comment by chutko** [comment]
this is my idea about the node size distribution. i think 2 buckets are enough:
1. nodes with smaller values - probably less important, their distribution is a long tail - most of the smaller values can produce tiny nodes of almost the same tiny size. as the value is approaching the second bucket, node sizes get bigger exponentially (fig.1). alternatively, they can follow linear function, but less steeper comparing to the second bucket (fig.2)

2. nodes with higher values - these will be possibly the important actors in the network. the size of these nodes are linear to their values. 

![elvis--nodesize-distribution](https://user-images.githubusercontent.com/4135015/33656836-a48df178-da77-11e7-9e6d-0312c2902dce.png)

**Comment by zufanka** [comment]
They are bigger and better now, not going to tinker with this more atm.
