### ISSUE TITLE
MyProjects page: use .project-list component on 

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#374]
In the issue #352 i have created a component for displaying list of projects. In this issue i would like to use this component and display My Projects in a more functional way than it is now.

**Comment by chutko** [comment]
i have already implemented the component into foreach loop and used most variables which were in the code. however, still there is some data missing, namely:
- public/private network indicator
- last updated date
- number of procurers, suppliers, connections
- number of companies (if) in the query

could @nightsh or @ca1yps0 have look at it? 
the branch name is `feat/myprojects`

after that, search/sorting/filtering could be the next step

**Comment by victor-nitu** [comment]
care to open a PR?
