### ISSUE TITLE
infobox: better appearance and placement

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#378]
formerly this infobox was designed to appear near the network node/edge on mouse over it. this solution was difficult to implement, so currently infobox appears at a steady position - in the top left corner of the network. 

in this issue i would like to discuss ways to improve the infobox user experience

**known problems:**
- according to user interviews, most users didnt notice when the box appeared. we need more eye catching appearance and possibly different position
- texts near the red flags inside the box are confusing, e.g. `percent_contracts` doesnt say much about why there is this flag. we need more self-explanatory texts for flags. 
- total flow/competition - same thing, this does not say much about the data. 
- a vertical scrollbar appears everytime infobox is shown

btw can this be used for the tooltip variant? 
http://jsbin.com/vaxagafiyi/1/edit?html,output

**Comment by chutko** [comment]
i have improved the visual of the infobox already. i hope it is more noticable and tidy now. 
if if would function like a tooltip over node/relationship, that would be the best

![elvis--infobox](https://user-images.githubusercontent.com/4135015/33477988-0f3df96c-d688-11e7-99f2-05b92363da60.png)

the text problems remain. also some values are hardcoded rather than called from variable values

**Comment by chutko** [comment]
@nightsh @ca1yps0 could you fix the hardcoded values?

**Comment by georgiana-b** [comment]
@nightsh In tenders-exposed/elvis-backend#69, the following changes to this payload have been made: 

- a field called `average_competition` has been added to each node for display in node details (contrary to what you said [here](https://github.com/tenders-exposed/elvis-ember/pull/379#issuecomment-348485568))
- `median` flag from nodes has been renamed to `average_competition`

**Comment by victor-nitu** [comment]
![image](https://user-images.githubusercontent.com/1579997/33488075-289deb44-d6b8-11e7-9720-c90eac4aa7ed.png)
This led to my error above. I suppose we need to regenerate every network in order to see it, right?

**Comment by georgiana-b** [comment]
Yes, only the  networks made from that commit on will have it

**Comment by victor-nitu** [comment]
ok, I will add it

**Comment by georgiana-b** [comment]
Also since we decided we are going to keep our flags, I suggest we do add some naming logic for them. For now our flags are

- average_competition: 1 - The average number of bids in these contracts is 1
- same_city: true - The supplier and procurer are from the same city

@zufanka Could you please suggest  phrases for these flags that will replace the flag name in the frontend?

**Comment by georgiana-b** [comment]
The flags from Digiwhist follow the pattern: 

```json
{
 "type": "ADMINISTRATIVE_COVERED_BY_GPA",
 "value": true
}
```

Where "ADMINISTRATIVE" is the category and "COVERED_BY_GPA" the flag, so we will need natural language "translation" for them too

**Comment by zufanka** [comment]
@georgiana-b I am suggesting them here: https://github.com/tenders-exposed/elvis-ember/issues/383

**Comment by victor-nitu** [comment]
Let's open a new issue for flag names, as it's not related to info box (we use them in some other places as well) – or maybe even tie it to #383.

Let's keep this about the infobox appearance and placement, as the title of the issue says.

**Comment by zufanka** [comment]
There is an issue with the template. Even if I visualize the amount of contracts, it says "Total money flow" with an M for some reason

The M needs to be removed. The "Total money flow" needs to be changed to "tenders" when visualizing amount of tenders

![image](https://user-images.githubusercontent.com/2411066/34258431-338bce3a-e65e-11e7-801e-ab9d6faecc48.png)

**Comment by zufanka** [comment]
![image](https://user-images.githubusercontent.com/2411066/34528511-70dfa748-f0a9-11e7-906b-bd5300d1624f.png)

It still says "money flow" instead of "tenders won" when clicking on the node
