### ISSUE TITLE
CPV selector has all the CPVs

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#380]
Instead only the first 4 levels

![image](https://user-images.githubusercontent.com/2411066/33437507-726e511c-d5e8-11e7-9e9d-29e6cb2739bb.png)

**Comment by victor-nitu** [comment]
is this a bug? 😮 

After the first 4 depth levels the hierarchy stops, and they are all put on the same branch (4th).
Now what you're saying is that we should skip them entirely. This is doable, but we're losing some scenarios, such as users hunting a very specific 4th+ level CPV code, which would be swallowed by its ancestor in this case.

**Comment by zufanka** [comment]
oh! then we misunderstood each other :) I thought the lower CPVs would get merged into the uppermost branch. Nevermind! Let's leave it like this for now if it's working as designed!
