### ISSUE TITLE
Clarify terminology

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#383]
**Sidebar:**
- remove ID 
- “count”  -> “amount of contracts”
- "sum"  -> “value of all contracts”

![image](https://user-images.githubusercontent.com/2411066/33474944-cc0b2de6-d67c-11e7-92db-0cc4ca4640a9.png)

**Infobubble:**
-  “count” -> “amount of contracts”
-  "sum"  -> “value of all contracts”
- red flag "x_same_city"  -> "company from the same city"
- red flag "median_bids" -> "mostly single bids"
(there should be no other red flags now afaik?)

![image](https://user-images.githubusercontent.com/2411066/33474954-d5f57e7e-d67c-11e7-9632-2b970387ac83.png)

**Detail view:**
- "total income" -> "The company acquired" X "from tenders in this view"
- "avg competition" -> "On average" X "companies bid on every of these tenders" 
- "data missing" -> "In" X "% of the tenders the value of winning bid is missing"

Not sure how to make this differently ^ . It requires more explanation, but perhaps we can solve it with tooltips? Ideas?

![image](https://user-images.githubusercontent.com/2411066/33475021-1f5557ba-d67d-11e7-8f68-a7f1c3f4f6a9.png)

**Comment by chutko** [comment]
also, remove "Sort By" from the sidebar select. if it is sorted by name by default, make this value selected

**Comment by victor-nitu** [comment]
Moving this request over to #368

**Comment by zufanka** [comment]
@georgiana-b we should have a look at other possible flags after you import the data

**Comment by zufanka** [comment]
fixed (except for the flags, not sure what they will be yet)
