### ISSUE TITLE
Sidebar and navbar should be open by default

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#384]
Users can not find it. It is better to have them open at loading and give the users opportunity to close them.

**Comment by victor-nitu** [comment]
That would increase our initial loading time quite a bit. Are we sure it's a good trade off?

**Comment by zufanka** [comment]
Hm .. not sure, ideas @chutko ?

**Comment by chutko** [comment]
to load the sidebar takes at most few seconds, i think its better if the user survives loading rather than not knowing about the existence of the sidebar

**Comment by victor-nitu** [comment]
🤷‍♂️ Fine, we'll transition to that route by default.
