### ISSUE TITLE
Clean up network tools and add tooltips

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#385]
Hover tootips:

![image](https://user-images.githubusercontent.com/2411066/33477204-222657fc-d685-11e7-9f9d-335bbb0bb117.png)

**Comment by victor-nitu** [comment]
The gears icon is on the physics on/off button. Pinging @chutko for better icons, these were merely some approximate choosings so we can put *something* on that button 🙂

**Comment by zufanka** [comment]
ah of course :) The icons are mostly fine. Tooltips will fix it. See updated picture.

**Comment by chutko** [comment]
for the gears icon, i would replace it with "play/stop" icon depending if the physics is on or off

for export, i would use a camera icon.

**Comment by zufanka** [comment]
@ca1yps0 could you also please add an icon and tooltip for "export data" ?
It would export the network data into a json.
