### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#387]
Display legend:

1. during loading
2. appear from the (?) button on the network tools.

**Comment by zufanka** [comment]
![image](https://user-images.githubusercontent.com/2411066/33478725-9a327a14-d68a-11e7-8528-8bb5090b5bef.png)

![image](https://user-images.githubusercontent.com/2411066/33478735-9ed028e6-d68a-11e7-8e2a-8d8901062f8f.png)

@chutko I thought we can have more of them. They could appear randomly on loading and alltogether from the (?) button. Here are two of them, but I would also do the network settings and side panel still.

The vector pdf of this is in storage Design > Legend (if you want)

**Comment by zufanka** [comment]
@chutko could you have a look at this perhaps still ^

**Comment by chutko** [comment]
during the loading, a modal could appear with this information. after the loading is finished, user can dismiss the modal. 

i also would like a small legend. i would like it to be visible all the time at the bottom, so the user knows all the time what colour is the government and what is the company

**Comment by chutko** [comment]
okay, i have something. feedback is very much welcomed

![elvis--loading-legend](https://user-images.githubusercontent.com/4135015/33799018-a68bc348-dd23-11e7-8aaa-e4329c2b4df9.png)

**Comment by zufanka** [comment]
very nice!

- typo: "FashionableCanes" 
- Government institution description: "amount of all tenders *awarded* by this institution"
- Supplying Company: "..symbolize companies that *won* tenders", ".. can represent how much money the company got, or how many tenders it won"
- Relationship: "intensity" instead of "richness" and "them" instead of "the actors"

**Comment by zufanka** [comment]
Can we put the legend in the loading screen?

**Comment by zufanka** [comment]
![image](https://user-images.githubusercontent.com/2411066/34257964-5c777346-e65c-11e7-840a-7c18a027c370.png)
This version @nightsh

**Comment by zufanka** [comment]
asked @chutko for a transparent picture

**Comment by victor-nitu** [comment]
![elvis--loading-legend-transparent-withoutloading](https://user-images.githubusercontent.com/1579997/36353641-8ba53010-14d1-11e8-87a0-345c84bee696.png)
