### ISSUE TITLE
Country selection in the Query builder

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#399]
Please change to:

**Select a country ... ... or Select and entity**
![image](https://user-images.githubusercontent.com/2411066/34258022-8c2a54b4-e65c-11e7-83e8-c2f0058e2baa.png)

Now user can select more than one country.
We however don't have anything in place that would visually distinguish the government country nodes. Would giving different colours to different government nodes be easy thing to do?
If not, I think we should limit the selection to one country only.

**Comment by victor-nitu** [comment]
Would it help to place a [country-code] label on procurer's name?
e.g. `[de] IBM GmbH`

**Comment by zufanka** [comment]
hm .. I think colours would work better, don't you?
Or is that trickier?

We only need different colours on governments btw, NOT on companies.

**Comment by zufanka** [comment]
we actually do need to address this, as an entity can be active cross-borders

**Comment by zufanka** [comment]
we'll do the country codes, but only if there are *two or more* countries present in the networks.
Only for governments, *NOT companies*!

**Comment by georgiana-b** [comment]
I don't know exactly why you went with the prefix but if we only wish to signal procurers I think different colors would be better.

**Comment by zufanka** [comment]
yes, I also thought so. But we had this conversation earlier in the call. Colours would require legend. Also, we would need to figure out how we represent the additional colors in the merging tool and on the side bar (as now all the governments are pink)

**Comment by victor-nitu** [comment]
@georgiana-b is this something you will do on the backend, or something we need to fix client side?

**Comment by victor-nitu** [comment]
ping @georgiana-b

**Comment by zufanka** [comment]
@nightsh @georgiana-b ping on this

**Comment by zufanka** [comment]
new QB fixes this
