### ISSUE TITLE
Standardize auth error handling

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#406]
- [ ] register
- [ ] login
- [ ] confirm
- [ ] recover

When errors are being sent from the server, use either the notifications service, or inline form errors, but make sure it's the same everywhere. We are allowed to make exceptions for displaying authentication errors to align with other widely used usability guidelines, but we must be consistent.

**Comment by georgiana-b** [comment]
Pls also make them pretty like in [the designs](https://storage.tenders.exposed/apps/files/?dir=/Design&fileid=85#/Design/elvis2--registration.png).

**Comment by victor-nitu** [comment]
Blocked by #474

**Comment by zufanka** [comment]
auth form has been redesigned. Is this sitll an issue @nightsh ?

**Comment by zufanka** [comment]
@nightsh update pls!

**Comment by victor-nitu** [comment]
Closing this, no auth errors detected except one that we have created a dedicated issue for: #513
