### ISSUE TITLE
"Other parties" in  supplier details is wrong

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#418]
In the `Other parties` column of contracts table  from supplier details the supplier is shown instead of the other suppliers and procurers involved in each contract:

![image](https://user-images.githubusercontent.com/8862002/36641631-7d6c0400-1a3b-11e8-89a5-1dc0ac82b073.png)

**Comment by zufanka** [comment]
This template is old afaik @georgiana-b

**Comment by georgiana-b** [comment]
It's a screenshot from Elvis production.

**Comment by georgiana-b** [comment]
I'll close this because it regards old templates.
