### ISSUE TITLE
Render edges of type `partners` i.e. consortia properly

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#423]
Currently the edges of type `partners` that mark a consortia between multiple buyers or bidders are rendered the same as a normal edge which looks confusing. For example the edges between the buyers in [this network](https://elvis-ember-new-backend.herokuapp.com/network/796dcf82-8216-46ac-aef3-da6be4c670e0/) are actually `partners` edges render wrong.

They should look dotted and with no arrows like in the drawing @zufanka  made a while ago:

![Antheater](https://talk.tenders.exposed/uploads/default/original/1X/f2cde1232a9c904a317d303ccd41d34584e9aae8.png)

**Comment by georgiana-b** [comment]
@zufanka Should we display these edges in the sidebar `Tenders` i.e. edges tab?

To me it sounds ok to show the edges info (same as below)  for `partners` edges too:

![image](https://user-images.githubusercontent.com/8862002/37090738-234c9eb4-220e-11e8-8011-294ff1074f64.png)

**Comment by zufanka** [comment]
@georgiana-b i am not sure I understand your question exactly, but I think we should not treat the special edges in the side bar or details in a way that would suggest they are tenders/bids.

**Comment by georgiana-b** [comment]
Ok, then @ca1yps0 please also remove these edge with `type: partners`  from the `Tenders` (edge details) tab. Currently they appear in the list even though requesting them from the server returns an error:

![image](https://user-images.githubusercontent.com/8862002/37216156-c4a6ee8a-23c2-11e8-9f95-c72ed5d55bd1.png)

**Comment by ca1yps0** [comment]
@zufanka @georgiana-b what about the box detail for this type of edges? do we still have one or not?

**Comment by georgiana-b** [comment]
Me and @ca1yps0 just decided in a call to show the details for  a consortium edge like this:

![image](https://user-images.githubusercontent.com/8862002/37719905-d62d32ca-2d2e-11e8-84a7-d5af7d78e9b5.png)

- instead of `Tender` write `Consortium`
- show the color corresponding to their type of node which should be the same for both
- instead of `x Bids won` write `x bids shared`
- remove `Show details` since we don't calculate details for `partners` edges

@zufanka Please review and comment the above. 

Now that I look at it I think `x bids together` would sound better.
