### ISSUE TITLE
[Company selector] If a space is used, search returns resutls for both words separately as well

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#440]
![image](https://user-images.githubusercontent.com/2411066/43514102-b9bb1ecc-957f-11e8-899b-5ba234341c95.png)

Solution: Show only results that contain both words.

**Comment by zufanka** [comment]
@georgiana-b is this a front end issue?

**Comment by zufanka** [comment]
parent issue: https://github.com/tenders-exposed/elvis-ember/issues/434

**Comment by georgiana-b** [comment]
No, this is definitely a backend issue. I will look into it later.

**Comment by georgiana-b** [comment]
This has been fixed so I'm closing this.
