### ISSUE TITLE
[Company selector] User messages

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#441]
1)
![image](https://user-images.githubusercontent.com/2411066/43513820-0af05c7c-957f-11e8-9c91-d28a8ec5b851.png)

*Should be:* Search for a company name or government institution. Use at least 3 characters.

2)
![image](https://user-images.githubusercontent.com/2411066/43514051-9ab76008-957f-11e8-8436-2dcd7ceb83fc.png)

If I use a space, it gives me an error message for some reason. If I writer further, it shows me resluts:

![image](https://user-images.githubusercontent.com/2411066/43514102-b9bb1ecc-957f-11e8-899b-5ba234341c95.png)

I think this is linked to the way the search works though. You can see it gives me results for 'duna' en for 'aszfalt' in the screenshot above here. It should NOT do this. See https://github.com/tenders-exposed/elvis-ember/issues/440

3)
![image](https://user-images.githubusercontent.com/2411066/43514366-5ca1c1e0-9580-11e8-96c6-4273033ee47d.png)

I don't know what went wrong here. I was backspacing.

**Comment by zufanka** [comment]
parent issue: https://github.com/tenders-exposed/elvis-ember/issues/434

**Comment by victor-nitu** [comment]
- [ ] fix scenario (1) - do no display "loading" when nothing is typed in
- [ ] fix scenario (2b) - construct Lucene queries from keywords before sending to API
- [ ] investigate (3) - crashes when deleting letters

**Comment by georgiana-b** [comment]
For 1. I created #482 
2.a. was solved in #440
For 2.b I created #481
3 doesn't seem to be valid anymore.

Having these said I will close this.
@zufanka it's much easier to keep track of issues if they refer to a single well defined problem. For the future let's try to keep them as modular as possible.
