### ISSUE TITLE
User should not be able to chose multiple unrelated CPVs

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#443]
Now people can chose unlimited amounts of sectors.

If however user selects let's say construction, all other branches should be grayed out.
They can still chose CPVs that are part of the same branch.

**Comment by zufanka** [comment]
blocked by https://github.com/tenders-exposed/elvis-ember/issues/444

**Comment by victor-nitu** [comment]
Not blocked anymore.

**Comment by zufanka** [comment]
ah whatever
