### ISSUE TITLE
[CPV selector] Use icons to bundle CPVs

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#451]
Instead of a flowchart like this:
![image](https://user-images.githubusercontent.com/2411066/44158075-419a7880-a0b4-11e8-93e7-32fb5d493c11.png)

Have icons that group select some CPV codes after you click them

**Comment by victor-nitu** [comment]
I cannot imagine this, could you give an example, a drawing, anything? :)

Will close as not enough info for the past half an year, but feel free to reopen if it's still relevant!
