### ISSUE TITLE
Change wording in Step 4

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#455]
![image](https://user-images.githubusercontent.com/2411066/44779485-e3739800-ab7f-11e8-8641-dcad08f73d0b.png)
I suggest changing "Node size" to "Dot size" and "Edge thickness" to "Connecting line" (to match the wording in the Legend, see https://github.com/tenders-exposed/elvis-ember/issues/446

**Comment by zufanka** [comment]
@chutko 

Could you share the pictures so @ca1yps0 can implement this?

![image](https://user-images.githubusercontent.com/2411066/44908392-8e6c8900-ad1b-11e8-8b8a-3a536b2d2968.png)

**Comment by chutko** [comment]
sure, here are the images. @ca1yps0 , the image size is 480x260px (for mobile), but on desktop use half the size 240x130px
![elvis-querybuilder-edgesize-](https://user-images.githubusercontent.com/4135015/44909762-d9d56600-ad20-11e8-9e9d-da73c4a6be22.png)
![elvis-querybuilder-edgesize-tenders](https://user-images.githubusercontent.com/4135015/44909763-da6dfc80-ad20-11e8-9ec4-00a2a609bdd6.png)
![elvis-querybuilder-nodesize-](https://user-images.githubusercontent.com/4135015/44909764-da6dfc80-ad20-11e8-8a8c-2649029696e5.png)
![elvis-querybuilder-nodesize-tenders](https://user-images.githubusercontent.com/4135015/44909766-da6dfc80-ad20-11e8-8143-1a009ea2a383.png)

**Comment by zufanka** [comment]
@ca1yps0 these should change as the user changes the options! Is it doable to do today still?
