### ISSUE TITLE
Merging two nodes doesn't merge them on the network

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#461]
![image](https://user-images.githubusercontent.com/2411066/46687061-35392480-cbfa-11e8-97a2-882ea7f3bf8e.png)

They just become two nodes ...

This is the network: https://tenders.exposed/network/1b535cfa-7220-4545-a581-d24217d7e0c6/bidders

**Comment by georgiana-b** [comment]
I just tested this on a new network and it works on now. @zufanka Maybe you found a specific case when it doesn't. Could you check that again?
