### ISSUE TITLE
Cluster details gets 500 because the request is made on `/nodes`

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#463]
At some point you could get a cluster's details either on:

`networks/{network_id}/nodes/{cluster_id}`

or on:

`networks/{network_id}/clusters/{cluster_id}`

Anyway, since the cluster payload s a little bit different that was changed so no you can **only** retrieve  a cluster's details on `networks/{network_id}/clusters/{cluster_id}`.

However, the frontend actually makes 2 requests when the node details are retrieved: 
 - one on `networks/{network_id}/nodes/{cluster_id}` which returns `500`
- one on `networks/{network_id}/clusters/{cluster_id}` which returns the right thing

Pls remove the request on `networks/{network_id}/nodes/{cluster_id}`.

**Comment by georgiana-b** [comment]
What exactly is blocking this @ca1yps0 ?

**Comment by victor-nitu** [comment]
Reopening as still valid.

**Comment by zufanka** [comment]
@nightsh still a problem?

**Comment by zufanka** [comment]
@nightsh does this relate to this? https://github.com/tenders-exposed/elvis-ember/issues/500

**Comment by zufanka** [comment]
@nightsh lallalala

**Comment by victor-nitu** [comment]
Request is pointing the right way now, closing this one...
