### ISSUE TITLE
Redesign query builder

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#475]
We need to redesign the query builder as a wizard with steps / navigation.

In this process we will also clean up the QB code and related services.

- [ ] implement the q.b. as a wizard
- [ ] implement the templates
- [ ] clean up the code

---

Mock-ups:

![image](https://user-images.githubusercontent.com/1579997/54085179-9bf67180-4343-11e9-9c91-2f0105c04fd3.png)
![image](https://user-images.githubusercontent.com/1579997/54085181-9f89f880-4343-11e9-89a1-9e6cee003cfe.png)
![image](https://user-images.githubusercontent.com/1579997/54085184-a284e900-4343-11e9-9ee7-4a8b2a07c1d8.png)
![image](https://user-images.githubusercontent.com/1579997/54085186-a4e74300-4343-11e9-9395-4d31306a0b3e.png)
![image](https://user-images.githubusercontent.com/1579997/54085189-a7e23380-4343-11e9-9d3b-887a76672ac1.png)

**Comment by georgiana-b** [comment]
@chutko @zufanka  I noticed you added a dropdown that says `Visualize all actors except` to the actor autocomplete template:

![](https://user-images.githubusercontent.com/1579997/54085181-9f89f880-4343-11e9-89a1-9e6cee003cfe.png)

Could you expand on that a little bit?
I can't imagine a scenario where journalists would want to exclude specific companies from the network. From what I understand the deal was either to select a few actors or all actors. It adds a lot of complexity to both the frontend and the backend to have both selection and exclusion and I'm not sure it's worth it.

As I see this actor select, there are 2 cases that need to be covered and conveyed to the user:
- the user chooses nothing (in which case all actors will be included in the network). I think the template should convey that it's possible to skip the step of filtering by actors if some countries have been chosen in the previous step
- the user chooses some actors, we filter by those, end of story

I'm imagining the layout something like:

```
Choose actors of interest:
[search input here]

Or choose all actors:
[] that have at least ... tenders
[] with awards higher than ... euros
```

WDYT?

**Comment by chutko** [comment]
the select above Actor select has two options: Visualise all actors except OR Visualise only these actors.

my intention was to add more custom options to the query which would help the user to build more specific (=faster) network. but if there is no such likely case, im ok with leaving that select out.

**Comment by zufanka** [comment]
> I can't imagine a scenario where journalists would want to exclude specific companies from the network. 

I can also hardly imagine that. 

> `Or choose all actors: ...`

This is actually and / or so ..

**Comment by zufanka** [comment]
@nightsh I think this is done, open separate issues for concrete problems
