### ISSUE TITLE
Add a network settings drop down

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#476]
We need a drop down with controls in the network view.

Design is still WIP, but we can implement the drop-down-that-shows-a-template thingy in the meantime.

![image](https://user-images.githubusercontent.com/1579997/54085240-89306c80-4344-11e9-998f-62c1aa377b17.png)

**Comment by chutko** [comment]
@nightsh @ca1yps0 my idea about this redesign is that all those buttons on the network populate tether dropdown. would be cool to make it work something like this:
```
<a href="#procurersList" {{action openProcurersList}}>P</a>
<div id="procurersList">content for procurers list is here...</div>
```

**Comment by zufanka** [comment]
@ca1yps0 do you have time to implement this?

**Comment by zufanka** [comment]
yay of nay? Discuss! @chutko @nightsh @ca1yps0 @georgiana-b

**Comment by victor-nitu** [comment]
This makes sense for larger networks - not for Defense Elvis.

**Comment by zufanka** [comment]
we don't have infra to generate too large networks either. closing
