### ISSUE TITLE
Display help message when user starts typing in autocomplete

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#482]
Currently a loading bar is displayed as soon as the user starts typing in autocomplete:

![loading](https://user-images.githubusercontent.com/2411066/43513820-0af05c7c-957f-11e8-9c91-d28a8ec5b851.png)

That is quite confusing, especially since no search is being performed until they type at least 3 characters.
Instead we should display a helpful message like the one proposed by @zufanka in #441:

`Search for a company name or government institution. Use at least 3 characters.`

The loading should appear only after they type at least 3 characters.

**Comment by georgiana-b** [comment]
@calypso Looks like this was almost solved except it starts the search after 2 letters. Could you please change that to 3 so that it fits the message?

**Comment by zufanka** [comment]
@ca1yps0 could you please implement this?

**Comment by zufanka** [comment]
@georgiana-b I guess we can close this issue
