### ISSUE TITLE
Manual data from Defense Elvis doesn't have CPVs

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#486]
The manually collected data which we will include in Defense Elvis does not have CPVs at all.

This means if we keep filtering by CPVs none of the manually collected data will be shown.

How do we work around this?

Are we eliminating the CPV selector from Defense Elvis?

Are we keeping the selector but adding an extra tick box to include the manual data?
I would personally prefer this option because the manual data is weird and I think people should be able to exclude it from the network if they want to.

**Comment by georgiana-b** [comment]
@zufanka I assigned this to you because we need your opinion on the subject.

**Comment by georgiana-b** [comment]
@zufanka @chutko Ping on this.

**Comment by georgiana-b** [comment]
In georgiana-b/defense-elvis-backend#6 I also added the field `CPV.military` to the CPV payload to mark those that are military.
That gives us the option to only display the military CPVs in the CPV selector but keep in mind that the manual data and the tenders imported on account of being part of the directive will not pass the filter by military CPVs.

**Comment by zufanka** [comment]
Sorry, I did not see this. It's a good question, I don't know how we should do this. I would actually prefer the collectors assigning a CPV to the tenders manually, as they know what they are about.

We can have that checkbox for sure, but we still need a way to categorize the manual data.

We can also opt for removing the CPV selector from the query builder, but I wonder whether we won't leave out an important part of filtering this way.

It could have other benefits though, like just caching whole country networks for 28 countries and not having them being built anew every time.

@nightsh @chutko what do you think?

**Comment by zufanka** [comment]
Will be fixed, closing for now @georgiana-b
