### ISSUE TITLE
Many query builder small issues

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#494]
Copied from [this PR](https://github.com/tenders-exposed/elvis-ember/pull/489#issuecomment-486433733).

There are still a couple of things to fix:

**BUGS**
- [x] if you don't select a CPV, the "Settings" step is empty. If the user doesn't chose any CPV, all of them will be selected. Could you please make this warning as such that it will be just yellow and say "If you don't chose any market, all the tenders will be selected. This may result in a slow network." and the user will be let to continue
- [x] if you go to "Create a network" from the network view (back to the query builder), the previous countries are actually still selected, but you don't see it in the first step (if you go a step further, the flags appear). Everything should be deselected if you do this
- [x] when I press "Launch the network", a loader should appear
- [oh well] flags missing here
![image](https://user-images.githubusercontent.com/2411066/56694788-ca5bc080-66e7-11e9-87a2-a06c09647cba.png)
- [x] This errormessage appears when server returns 500. This should NOT be the case as it's NOT the problem. Can we change it to "This should not be happening. Please send us an email at tech@tenders.exposed if it is." or something like that?
![image](https://user-images.githubusercontent.com/2411066/56694959-3ccca080-66e8-11e9-9f4d-979af5a47ff5.png)
- [x] if not chosing a country nor a company, there is an error. That is good, but it should disappear once you go back and chose a country
![image](https://user-images.githubusercontent.com/2411066/57774991-4613c080-771c-11e9-818a-be5977d58d33.png)
- [x] if not chosing a CPV, there is a warning. This is good, but I still can not go further. Please add to the warning "Proceed anyway" with a different color and link to the following step in the query builder. Also please release the lock on 'next' here.
![image](https://user-images.githubusercontent.com/2411066/60330051-e7d03380-9991-11e9-954c-010165d3f4e3.png)

**STYLING**
- [x] this selection goes into the footer. Please give the element the same height all the steps in the the whole wizard
![image](https://user-images.githubusercontent.com/2411066/56692515-a649b080-66e2-11e9-8f01-45865be27adc.png)
- [x] there should be more space between these
![image](https://user-images.githubusercontent.com/2411066/56694220-7f8d7900-66e6-11e9-8eaf-fedc710a7806.png)
- [x] there should be definitely more space here
![image](https://user-images.githubusercontent.com/2411066/56694285-a21f9200-66e6-11e9-8341-a3ce66a1fb46.png)
- [x] the "Node types" and "edge types" as well as the "name of the network" are a bit small and difficult to read. @chutko can we make them pop out more?
![image](https://user-images.githubusercontent.com/2411066/56694365-c5e2d800-66e6-11e9-8520-a026dcbf65b2.png)
- [x] can we have these on a transparent background? @chutko 
![image](https://user-images.githubusercontent.com/2411066/56694398-d5fab780-66e6-11e9-87cc-20cca19522ca.png)
- [ ] colors don't match here (for DEFENSE ELVIS)
![image](https://user-images.githubusercontent.com/2411066/57775048-70fe1480-771c-11e9-9699-7cb10c8af9a5.png)
- [ ] There should be some indicator that the user chose actors here (no countries chosen now)
![image](https://user-images.githubusercontent.com/2411066/56694859-0000a980-66e8-11e9-9d3a-d04b9165bb2b.png)
- [ ] The carousel colors need to be adapted as well (for DEFENSE ELVIS)
![image](https://user-images.githubusercontent.com/2411066/57775200-c76b5300-771c-11e9-835e-4a895571ecfb.png)
- [ ] The carousel has to be way bigger. At least 1000 px wide (now it's 678 px)

**Comment by chutko** [comment]
i have fixed most of the issues and improved the styles. however, i was not able to test everything because neither any countries were displayed nor the actor select was working so i could not get forward

you can find it all in `fix/query-builder-styling`

**Comment by zufanka** [comment]
@chutko thank you! The countries are displaying now. I have added one minor thing in the styling.

**Comment by zufanka** [comment]
most of this is fixed, will open a new issue for the rest
