### ISSUE TITLE
network redraw after clustering fails

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#500]
![image](https://user-images.githubusercontent.com/2411066/59057057-d2d41900-8899-11e9-83e3-e9272f87d2ea.png)

**Comment by zufanka** [comment]
@ca1yps0 fixed this I believe in https://elvis-ember-develop-pr-502.herokuapp.com/, would you make sure it's merged?

**Comment by zufanka** [comment]
This is still very much an issue!! @nightsh , could we merge it please?

**Comment by victor-nitu** [comment]
Likely fixed by #502 - testing needed.

**Comment by zufanka** [comment]
fixed as far as I could see.
