### ISSUE TITLE
[Defense Elvis] Replace Tender Details page with link to source

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#505]
Manual data is missing most of the values that we normally display in the Tender Details page. 
Therefore we decided to remove the Tender Details page in Defense Elvis and instead link to the source of the tenders directly in the Contracts table:

![node-details-elvis](https://user-images.githubusercontent.com/8862002/77154033-36cb7500-6a9b-11ea-8d54-0441e4a67654.png)

TODO:

- [ ] remove the Tenders Details page
- [ ] add another column for `year` in the Contracts table where we display `tender.year`
- [ ] when clicking on the title of the tender, instead of linking to the Tender Details page we will link directly to the first link in `tender.sources`

**Comment by zufanka** [comment]
done!
