### ISSUE TITLE
Side bar floating away 

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#518]
The original look:

![image](https://user-images.githubusercontent.com/2411066/79219978-7e071480-7e53-11ea-9c29-1802807d10e9.png)

The original problem:

![image](https://user-images.githubusercontent.com/2411066/79219245-30d67300-7e52-11ea-9bf1-eb9d8ecfd79a.png)

Ioana tried to fix this, and she did, but it does not work on my resolution (it does in hers)

![image](https://user-images.githubusercontent.com/2411066/79220802-020dcc00-7e55-11ea-81dd-6fc765cefaf4.png)

This is what it's supposed to look like (ish):
![image](https://user-images.githubusercontent.com/2411066/79219410-83b02a80-7e52-11ea-81e9-df149296739f.png)

Since you made the template, could you have a look please?

example network: https://defense.tenders.exposed/network/d1e061d4-3845-40c0-b067-eb65fc089b80/bidders/fc6154e4-3442-44b3-a7a2-7222270e4cd0

**Comment by chutko** [comment]
fixed https://github.com/tenders-exposed/elvis-ember/pull/529
