### ISSUE TITLE
Handle unknown average competition

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#520]
![image](https://user-images.githubusercontent.com/2411066/79351900-833e8f00-7f39-11ea-8fb1-6b9699ba81ce.png)

It should say "?" or "unknown"

**Comment by zufanka** [comment]
Still does not seem to be fixed 
![image](https://user-images.githubusercontent.com/2411066/79999197-ee4d1000-84bb-11ea-94e8-75ad4d139770.png)

?

**Comment by ca1yps0** [comment]
it now says 'value unknown'
