### ISSUE TITLE
Login timeout if session expired

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#67]
Check with backend Devise settings for how long a session token is valid.

**Comment by georgiana-b** [comment]
@nightsh [2 weeks](https://github.com/tenders-exposed/elvis-backend/blob/master/config/initializers/devise.rb#L27)

**Comment by victor-nitu** [comment]
Blocked by backend migration, as we'll have a completely different auth mechanism.

**Comment by zufanka** [comment]
ping @nightsh is this still relevant?

**Comment by victor-nitu** [comment]
Yes, but it is currently blocked by the new authentication system. Will deal with it after we have another backend.

**Comment by georgiana-b** [comment]
I think it's safe to close this in favor of #414
