### ISSUE TITLE
Network manipulation controls

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#71]
On the network controls, redefine what nodes / edges mean.

NB: This currently has unwanted side effects, such as:

* the process generates a new network
* the old network is left behind
* the URL changes

Might want to rethink the process if these are a problem.

**Comment by zufanka** [comment]
What does this mean exactly?

**Comment by victor-nitu** [comment]
We will deal with this after switching over to the new backend. This issue is related to redefining some query params on a network, which still has a few unknown / undefined parts.

**Comment by victor-nitu** [comment]
@zufanka is this still a thing?
