### ISSUE TITLE
Generate and show thumbnails for networks

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#73]
On generating a network, save a thumbnail after the first stabilization.

How I see it (roughly):

* stabilization cycles are done
* canvas gets saved in a PNG into a localForage key
* make sure you're not sending a mountain of pixels (i.e. is not a huge image)
* the result is then POSTed to backend and saved as one of the network's attributes

**Comment by nightsh** [comment]
Blocked by tenders-exposed/elvis-backend#31

**Comment by zufanka** [comment]
@nightsh @chutko we won't create thumbnails. too much work, not that important. Related: https://github.com/tenders-exposed/elvis-ember/issues/352
