### ISSUE TITLE
Related entities tables in details page

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#78]
Populate a table with the related entities, as in the mock up.

![07-supplier-contracts](https://cloud.githubusercontent.com/assets/1579997/20722194/532e9630-b66e-11e6-97a7-ccaae3172013.png)

**Comment by zufanka** [comment]
is this still not implemented?

**Comment by nightsh** [comment]
I think it's closeable. @ca1yps0?
