### ISSUE TITLE
Contracts subroute from the details page

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#79]
This should probably be split in two at the moment of fixing:

- [ ] contract details
- [ ] tender details

![09-contract-details](https://cloud.githubusercontent.com/assets/1579997/20722278/9a24a480-b66e-11e6-8a67-a56f4b167bd7.png)

**Comment by zufanka** [comment]
Is this not already implemented?

**Comment by nightsh** [comment]
Almost, we're missing a few nuts and bolts. @ca1yps0, do you have any updates on this?

**Comment by chutko** [comment]
if you have some questions, just ask
