### ISSUE TITLE
Projects list data preview

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#86]
In the project "card" in the listing, make sure we show as much as we can of the following:

- [ ] number of nodes
- [ ] number of edges
- [ ] list of chosen CPV codes

**Comment by nightsh** [comment]
Temporarily blocked by tenders-exposed/elvis-backend#37

**Comment by zufanka** [comment]
ping @nightsh ..
what do you mean with "network card" ?? Is it related to https://github.com/tenders-exposed/elvis-ember/issues/352 ?

**Comment by victor-nitu** [comment]
Yes, closing this one as the other one has more complete and up to date info.
