### ISSUE TITLE
Unified loader throughout the app

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#88]
- [ ] Consistently use the router loading state to implement loading messages and templates.
- [ ] Use a unique (animated) loader to show all the full page messages.
  - [ ] Ideally, use the loader provided by #107 
    - [ ] however, this is not blocking the issue, we could use anything until #107 is fixed :)

**Comment by nightsh** [comment]
we can also use this animated canvas from [here](https://osf.io/) – code is open source, we can remix the very simple JS code doing that into whatever we want, if we end up liking the idea :)

For the record, the (most) relevant code is here: https://github.com/CenterForOpenScience/osf.io/blob/08a604c550c68c53653bf751ccd0571acc50cab4/website/static/js/pages/landing-page.js#L57-L108

**Comment by zufanka** [comment]
I love that network animation, makes me think of spiders a bit tho :) But it's super cute.
Where do we need the loader except for loading the network?

**Comment by chutko** [comment]
#107

**Comment by zufanka** [comment]
@chutko @nightsh can we do the network loader? I will close 107, it's the same.

**Comment by chutko** [comment]
i hoped we will approach the loading from all sides as described in #107 

if you guys really want to use the loader linked above, lets try. other option is to just use some nice plugin or animation

**Comment by victor-nitu** [comment]
This is a slightly more technical issue, focusing on some Ember specifics rather than the design of it. I will adjust it to make a bit clearer, as loading is a twofold action, it requires a design and a framework implementation.

Or we can just keep a single issue and pass the ball from design to development or the other way around. But as of now, I think they're overlapping a bit more than needed :)

**Comment by zufanka** [comment]
@nightsh @chutko so where is the ball now?

**Comment by chutko** [comment]
personally i think the loading animation should be handled by pure CSS. the HTML element containing the loading animation (+overlay etc) should be displayed just by switching class. 

HTML: 
`<div class="loading is-loading"><animated-stuff-html></animated-stuff-html></div>`

CSS:
```
.loading {
   display: none;
   [...spinning stuff css...]
}
.loading.is-loading {
   display: block;
}
```
