### ISSUE TITLE
Export to csv (and excel if possible)

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#90]
Not graph file, but *(de-)clustered* info on the contracts. Potentially useful for users to do further analysis on. Excel not mandatory, but way too many people don't know what a .csv is :)

**Comment by chutko** [comment]
@zufanka i see this as future feature, maybe we can have label for that?

**Comment by victor-nitu** [comment]
Closing for now, will reopen when/if we will ever want it again.
