### ISSUE TITLE
CPV selector goes bonkers

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#93]
Create a new network > marvel at the beauty > click "New visualization" in the upper menu > Add CPVs >

![image](https://cloud.githubusercontent.com/assets/2411066/20754696/6e5b5f6c-b70c-11e6-8922-ae2ab7202ab3.png)

The same on Chrome and Firefox

**Comment by ca1yps0** [comment]
retest using the staging server staging.elvis.tenders.exposed
